### ISSUE TITLE
iojs-full without upgraded npm

### ISSUE THREAD

**Issue by mickhansen** [mhart/alpine-node#1]
node-gyp will fail in a lot of cases if one doesn't use the npm bundled with iojs.
It would be great to be able to use your alpine-iojs package but without the `npm update -g npm` part here: https://github.com/mhart/alpine-node/blob/master/Dockerfile.full#L21

**Comment by mhart** [comment]
That's a bit strange – so you can't update npm at all? That sounds like a bug with npm and/or io.js – why would it suddenly stop working if it updates?

You sure that node-gyp works fine on Alpine Linux in the first place? I suspected that musl libc prevented many native modules from building at all.

Have you got an easy way to reproduce this?

**Comment by mickhansen** [comment]
I can use npm, i can't use packages that use node-gyp. It's a bug with node-gyp that's fixed in the npm version bunded with io.js. (https://github.com/TooTallNate/node-gyp/pull/564, https://github.com/iojs/io.js/issues/433)

It works just fine if i copy your dockerfile and remove the `npm update -g npm` part. (and install a few extra packages).

Repro something like:

```
FROM mhart/alpine-iojs

RUN apk add python openssl libgcc make libstdc++ apk add g++
RUN npm install ursa
```

**Comment by mickhansen** [comment]
Although now i end up with a 400mb image, so not a huge gain anymore.

**Comment by mhart** [comment]
Ok cool – I'll look into this and let you know if I come up with something better!

**Comment by mickhansen** [comment]
I think that removing the npm upgrade and letting users do it themselves seems fine, but that's up to you obviously.

**Comment by mhart** [comment]
Well I think a solution that allows the latest version of npm is best – I mean, it doesn't make sense to have to be stuck on an old version and not be able to upgrade.

**Comment by mickhansen** [comment]
Of course, but the user can always run `npm update -g npm` on his own if he so wishes (without having to affect other people who need the bundled version for node-gyp).
iojs moves pretty fast and there's usually a pretty new npm bundled with it (1.7.1 has the private repos npm installed for one).

**Comment by mhart** [comment]
Well, I've rebuilt and pushed as `mhart/alpine-iojs` with tags `latest`, `1.7` and `1.7.1` – let me know if that fixes it for you.

**Comment by mickhansen** [comment]
It does, thank you.
