### ISSUE TITLE
auto downgrade to nodejs v6.x when install angular cli

### ISSUE THREAD

**Issue by bolerap** [mhart/alpine-node#101]
Hi all.
I'm trying to install angular cli with command `npm install -g @angular/cli` on nodejs v8.2.1 but when the above command complete nodejs automatically be downgrade to version 6.x.
How can i fix it?
many thanks.

**Comment by mhart** [comment]
@thanhngvpt I can't reproduce this:

```
$ docker run -it mhart/alpine-node:8.2.1 sh
/ # npm install -g @angular/cli
...
/ # node --version
v8.2.1
```

There are currently issues with npm v5.3.0 and angular/cli – which you can see here https://github.com/mhart/alpine-node/issues/100 and here https://github.com/npm/npm/issues/17851

But neither of those describe what you're seeing.

Can you please post the steps to reproduce – or the relevant portions of your Dockerfile?

**Comment by bolerap** [comment]
Thanks for your reply @mhart That weird, The steps I walked same you except use yarn instead of npm. BTW, I've solved it by accept v6.x, Will retry it with v8 for dev env.
