### ISSUE TITLE
Yarn 1.0.2

### ISSUE THREAD

**Issue by nikz** [mhart/alpine-node#103]
Hiya @mhart,

First off, thanks for the Dockerfiles!

Secondly, would you be able to rebuild the `8`-series images on Docker Hub so that we get `yarn` version 1.0.2 (which is [the latest](https://github.com/yarnpkg/yarn/releases/tag/v1.0.2) as of ~24 hours ago). This would help us get past a particularly troublesome "404" bug for private packages.

Thank you!

Nik

**Comment by mhart** [comment]
I wouldn't normally do this – patch releases in tools like npm and yarn happen regularly and aren't worth the effort – if users need them they should handle them in their own Dockerfiles...

BUT, seeing as I've been bitten by this particular bug myself, I went ahead and did it THIS ONE TIME 😸

**Comment by nikz** [comment]
@mhart Ha! Yes that's absolutely fair, and we were working around by installing yarn nightly but that just felt a little too hacky.

Thanks for the fast change! :shipit: 🚀
