### ISSUE TITLE
3.4 => 3.6 upgrade

### ISSUE THREAD

**Issue by Vanuan** [mhart/alpine-node#104]
Looks like all tags were upgraded to 3.6 as a base alpine image.
This broke my builds (I've used it as a base image to install additional apk packages).
Moving to an official node image. Hopefully they'll keep old tags as is.
I've seen a practice to specify a version of alpine in a tag name. E.g.:

- node:6.8-alpine3.4
- node:6.8-alpine3.6

**Comment by mhart** [comment]
@Vanuan what version are you running? Only Node v8.x is on Alpine 3.6 – Node v6.x is still on 3.4:

https://github.com/mhart/alpine-node/commit/ca4aa1353910b43eaac49f45b1f560f90ac139e0

**Comment by mhart** [comment]
Whenever the Node major bumps, I also bump to the latest Alpine. It's a major bump, so not backwards compatible

**Comment by mhart** [comment]
Confirmed, older versions are still on 3.4. Not sure how you would've upgraded to 3.6 unless you weren't pinning the version of the image.

```console
$ docker run mhart/alpine-node:base-4 cat /etc/alpine-release
3.4.6
$ docker run mhart/alpine-node:base-6 cat /etc/alpine-release
3.4.6
$ docker run mhart/alpine-node:base-8 cat /etc/alpine-release
3.6.2
```

Closing this, but feel free to reopen if you get different results

**Comment by Vanuan** [comment]
Apparently, this has nothing to do with 3.4 => 3.6
I was pinning the versions of ruby packages. Ruby in 3.4 was upgraded from 2.3.1 to 2.3.5 so it failed with unsatisfiable constraint.
