### ISSUE TITLE
Installing Yarn & NPM - why not apk-add?

### ISSUE THREAD

**Issue by bkuhl** [mhart/alpine-node#106]
Is there a reason you don't install yarn and npm using the standard packages?

https://yarnpkg.com/lang/en/docs/install/#alpine and https://superuser.com/a/1187246

**Comment by mhart** [comment]
@bkuhl yes, because they have (or at least had?) a dependency on the node.js apk package.

So installing yarn via apk will also install node.js via apk (which is a different version from what this image uses)

**Comment by mhart** [comment]
You can see more discussion about this here: https://github.com/yarnpkg/yarn/issues/1326
