### ISSUE TITLE
Specific examples where musl-libc can be problematic?

### ISSUE THREAD

**Issue by samlevin** [mhart/alpine-node#107]
I've been using alpine-node for a bit and find it useful (and minimal). Great base image. In the readme, you mention:
```
As Alpine Linux uses musl, you may run into some issues with environments expecting glibc-like behavior – especially if you try to use binaries compiled with glibc. You should recompile these binaries to use musl (compiling on Alpine is probably the easiest way to do this).
```
Are there any notable/common problem areas surrounding this? So far I've read that one such example is OracleJDK 8. Are there any other common libraries (for node use-cases) that require glibc? If so, can they be fully worked-around by compiling them against musl-libc? Are there any observed instances where this caveat cannot be worked around?

**Comment by mhart** [comment]
It mostly affects things where there are prebuilt binaries that don't distinguish between glibc and musl – like for example https://www.npmjs.com/package/phantomjs-prebuilt

**Comment by mhart** [comment]
Whereas in an ideal world, companies/ppl would provide binaries prebuilt for both systems, eg: https://zeit.co/download#command-line (`now-linux` *and* `now-alpine`)

**Comment by samlevin** [comment]
Thanks for the info @mhart!
