### ISSUE TITLE
risingstack

### ISSUE THREAD

**Issue by stychu** [mhart/alpine-node#108]
Hello. Im trying to make image from this dockerfile

```
FROM mhart/alpine-node:6

RUN apk --no-cache add git
WORKDIR /app
COPY package.json .
RUN npm install

COPY . .

EXPOSE 3000
CMD ["node", "server/server.js"]
```

but I keep getting the this error. Any help appreciated. Thanks! 

> npm ERR! Linux 4.4.0-72-generic
> npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
> npm ERR! node v6.11.3
> npm ERR! npm  v3.10.10
> npm ERR! code ELIFECYCLE
> 
> npm ERR! @ risingstack/v8-profiler@5.7.11 install: `node-pre-gyp install --fallback-to-build`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the @risingstack/v8-profiler@5.7.11 install script 'node-pre-gyp install --fallback-to-build'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the @risingstack/v8-profiler package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node-pre-gyp install --fallback-to-build
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs @risingstack/v8-profiler
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls @risingstack/v8-profiler
> npm ERR! There is likely additional logging output above.

**Comment by mhart** [comment]
Looks like `npm` is failing to install `@risingstack/v8-profiler`

If it requires native compilation (which it probably does given that's it's trying to use `node-pre-gyp`), then you'll need to install some more dependencies – the example in the README should be enough: https://github.com/mhart/alpine-node#example-dockerfile-for-your-own-nodejs-project

```
RUN apk add --no-cache make gcc g++ python
```
