### ISSUE TITLE
gpg: keyserver receive failed: Address not available

### ISSUE THREAD

**Issue by mdgreenwald** [mhart/alpine-node#109]
Hi,

I think you just need to add this key:
`9554F04D7259F04124DE6B476D5A82AC7E37093B`

From https://github.com/nodejs/node#release-team

And it will resolve this issue for those of us looking to compile a specific non-tagged version such as 8.2.0.

Thanks

**Comment by mhart** [comment]
@mdgreenwald you can browse older releases by checking out the appropriate git tag (I remove keys when they're no longer used)

https://github.com/mhart/alpine-node/tree/8.2.0

**Comment by mhart** [comment]
(is there a reason you're trying to compile an old release instead of just using it as the `FROM` image in your Dockerfile btw?)

**Comment by mhart** [comment]
Also – the error that you have in the issue title doesn't seem to match anything to do with not using the correct key – it looks more like a network error trying to contact the gpg keyservers to me.

**Comment by mhart** [comment]
Closing this – feel free to reopen if you think I've misinterpreted the issue
