### ISSUE TITLE
How do you build this project?

### ISSUE THREAD

**Issue by chrisabrams** [mhart/alpine-node#11]
I get the following error when running Docker on Ubuntu 15.04:

OK: 177 MiB in 52 packages

Executing busybox-1.23.2-r0.trigger
Executing ca-certificates-20141019-r2.trigger
tar: invalid magic
tar: short read
INFO[0028] The command [/bin/sh -c apk add --update curl make gcc g++ python linux-headers paxctl libgcc libstdc++ &&   curl -sSL https://nodejs.org/dist/${VERSION}/node-${VERSION}.tar.gz | tar -xz &&   cd /node-${VERSION} &&   ./configure --prefix=/usr ${CONFIG_FLAGS} &&   make -j$(grep -c ^processor /proc/cpuinfo 2>/dev/null || 1) &&   make install &&   paxctl -cm /usr/bin/node &&   cd / &&   if [ -x /usr/bin/npm ]; then     npm install -g npm@2 &&     find /usr/lib/node_modules/npm -name test -o -name .bin -type d | xargs rm -rf;   fi &&   apk del curl make gcc g++ python linux-headers paxctl ${DEL_PKGS} &&   rm -rf /etc/ssl /node-${VERSION} ${RM_DIRS}     /usr/share/man /tmp/\* /var/cache/apk/\* /root/.npm /root/.node-gyp     /usr/lib/node_modules/npm/man /usr/lib/node_modules/npm/doc /usr/lib/node_modules/npm/html] returned a non-zero code: 1

**Comment by mhart** [comment]
That looks like curl is getting a file that doesn't exist – what did you run this with?

**Comment by chrisabrams** [comment]
I tried getting node 4.2.1, which you said didn't exist yet over here: https://github.com/mhart/alpine-node/pull/10

So I'll wait until 4.2.1 is out and try agian.

**Comment by mhart** [comment]
Yeah, you can see the latest version here: https://nodejs.org/en/ – v4.2.0
