### ISSUE TITLE
VERSION environment variable possible conflicts

### ISSUE THREAD

**Issue by gryphon** [mhart/alpine-node#110]
Hello!

I think it is better to rename VERSION variable to NODE_VERSION because it may cause some problems with using this image. For example, some ruby applications use this variable and conflicts are bit annoying. 

Thank you!

**Comment by mhart** [comment]
Changing this would be backwards incompatible unfortunately – for ppl relying on it. Probably best just to change it in your Dockerfile if you need it for something else.
