### ISSUE TITLE
Could curl stay?

### ISSUE THREAD

**Issue by markg85** [mhart/alpine-node#111]
Hi,

The dockerfile installs and removes curl.
For most users that is probably just fine.

But in one of my node micro services i use the "curlrequest" module. That is just a curl wrapper for node.js. Using that (or curl in general) makes it rather easy to do web requests. I am aware that the same can be done using the http build in module, but that is a lot more low level and imho less user friendly then using curl via curlrequest.

Therefore i hope you could consider changing the dockerfile to not remove curl.

Best regards,
Mark

**Comment by mhart** [comment]
Hi Mark, you can just add it back in your Dockerfile:

```Dockerfile
FROM mhart/alpine-node:8

RUN apk add --no-cache curl
```
