### ISSUE TITLE
gRPC issue on node8

### ISSUE THREAD

**Issue by gl-lamhnguyen** [mhart/alpine-node#119]
I was trying to run Meteor RocketChat from node8 image and got the following error:

```
Failed to load gRPC binary module because it was not installed for the current system
Expected directory: node-v57-linux-x64-musl
Found: [node-v46-linux-x64-glibc]
```

Not sure what to do here?

**Comment by mhart** [comment]
Alpine doesn't have glibc by default, it uses musl – more info here: https://github.com/mhart/alpine-node#caveats

**Comment by mhart** [comment]
It's an issue with gRPC, see here: https://github.com/grpc/grpc/issues/10560

**Comment by gl-lamhnguyen** [comment]
Thanks for reply. Is it something I can find a work around or I have to find another base image?

**Comment by mhart** [comment]
It should work with any glibc based image – like `docker run node:8`
