### ISSUE TITLE
LTS tag?

### ISSUE THREAD

**Issue by goloroden** [mhart/alpine-node#12]
Now that Node.js has an LTS version, might it be a good idea to also have an `lts` tag here?

**Comment by mhart** [comment]
Hmmm, mayyyybe. I'm not so convinced though. If you select `lts`, that has no semantic versioning guarantee – so the minute Node.js chooses to change `lts` from `4.x` to `5.x`, everyone's stuff could break.

Unless there's like a `4-lts` tag or something like that...

**Comment by hmalphettes** [comment]
We have had this discussion at docker-node and we settled on tagging v4 with `argon`:
https://github.com/nodejs/docker-node/issues/52

v5 is getting the usual `latest` tag.

**Comment by mhart** [comment]
It's still a bit unclear to me how `argon` would be different from `4.2` (or `4` if LTS is allowing new features)

I kinda feel like sticking with semver semantics will have the least surprises for people.

**Comment by mhart** [comment]
So it's been a while now, and a few version later – the LTS tag to use is `4` – I think there's no need to add another tag that's an alias of that. Thanks for the feedback though!

**Comment by dentuzhik** [comment]
I think one way you approach this would be to use the same convention as `nvm` uses:
https://github.com/creationix/nvm#long-term-support

So users could use something like `lts/argon`, `lts/carbon`, etc

**Comment by mhart** [comment]
@dentuzhik Users can just use `8`, `6`, etc
