### ISSUE TITLE
Can not pull latest

### ISSUE THREAD

**Issue by toshi38** [mhart/alpine-node#120]
Attempting to pull the latest from docker hub fails with mhart/alpine-node:latest not found (see below).  However pulling a specific version still works.

Is latest deprecated for some reason?

```
stephen@stelau-ubuntu:~/code$ docker pull mhart/alpine-node
Using default tag: latest
Error response from daemon: manifest for mhart/alpine-node:latest not found
stephen@stelau-ubuntu:~/code$ docker pull mhart/alpine-node:9
9: Pulling from mhart/alpine-node
ff3a5c916c92: Pull complete 
e474f1a1f25f: Pull complete 
Digest: sha256:8c5ddfc0a4af4ee67f4c02c69a51d3bbe1ff84c5633c60a4e5f6c47213198e07
Status: Downloaded newer image for mhart/alpine-node:9
stephen@stelau-ubuntu:~/code$ 
```

**Comment by mhart** [comment]
Not sure what's going on there – it was pushed with the others as you can see here: https://hub.docker.com/r/mhart/alpine-node/tags/

**Comment by toshi38** [comment]
Weird... maybe its a docker-hub bug of some sort.  It seems to be resolving again now.  Both locally and in our Travis environment, both of which where failing before.

No idea why they where failing, but seem to be fixed now.

Thanks for the quick reply and cheers for the super helpful images!
