### ISSUE TITLE
node:10-alpine not npm@6.0.0

### ISSUE THREAD

**Issue by wallzero** [mhart/alpine-node#121]
Greetings,

I started running my builds in the latest `node:10-alpine` image expecting to use the latest [`npm ci` command](https://blog.npmjs.org/post/171556855892/introducing-npm-ci-for-faster-more-reliable). I believe `npm ci` has been available since `npm@5.7.0`. However, it appears `node:10-alpine` is still using `npm@5.6.0`. See my GitLab build [here](https://gitlab.com/wallzero/webpack-digest/-/jobs/65801087).

Thanks!

**Comment by mhart** [comment]
I think you've got the wrong repo – this has the `mhart/alpine-node` images

**Comment by styfle** [comment]
Related: https://github.com/nodejs/docker-node/issues/709
