### ISSUE TITLE
busybox adduser creates home directory with "-H" option

### ISSUE THREAD

**Issue by matinats** [mhart/alpine-node#122]
Hi,

I am using alpine 3.6.2 and noticed that when using adduser to add a new user when I specify the "-H              Don't create home directory" option it creates a home directory.

Using BusyBox v1.26.2.

`adduser -u 666 -s /sbin/nologin -H -D -g "bela process user" bela bela`
`cat /etc/passwd | grep bela`
`bela:x:666:666:bela process user:/home/bela:/sbin/nologin`

Regards

**Comment by mhart** [comment]
Hi @matinats – this repo is actually a distribution of Node.js built on top of Alpine – not the Alpine repo itself.

You might find an answer to your question (or a better place to ask it) at https://wiki.alpinelinux.org/wiki/Alpine_Linux:FAQ
