### ISSUE TITLE
No latest-lts tag

### ISSUE THREAD

**Issue by samuelms1** [mhart/alpine-node#125]
It would be awesome if there was a `latest-lts` tag that could be used to guarantee we're always using the latest LTS version of Nodejs on the alpine-node image.  Right now my team is using the `latest` tag but we'd really prefer to be on the latest LTS version of Nodejs.

There has been some internal discussion around this since the odd major versions of nodejs can (and have) had bugs (like the memory leak in version 7).  So, to avoid coming across issues like this it's becoming increasingly important to use the LTS.  Is the `latest` tag only applied to builds where the major version is an even number?

**Comment by mhart** [comment]
This was discussed in https://github.com/mhart/alpine-node/issues/12

Basically, you shouldn't be using `latest` or `lts` (not in production anyway) – it's too dangerous because the major can bump at any time.

Much better to stick with `10` or `8` if this is what you want.

**Comment by samuelms1** [comment]
Thanks @mhart for the quick response.
