### ISSUE TITLE
Where is the node 5 image ?

### ISSUE THREAD

**Issue by vitoo** [mhart/alpine-node#126]
Hello,

I need the node 5.12.0 image for an old project. 
Why there is no image for this version 5 ?

I will try to build it 

Thanks you

**Comment by mhart** [comment]
I'm not sure what you mean.

```
$ docker pull mhart/alpine-node:5.12.0
5.12.0: Pulling from mhart/alpine-node
e110a4a17941: Pull complete 
ed5811933fda: Pull complete 
Digest: sha256:9da75ebafa08bac5964d3df371252088d35c6feae7dec2afc4e091b582ec60c6
Status: Downloaded newer image for mhart/alpine-node:5.12.0
```

Works fine for me. Closing.

**Comment by vitoo** [comment]
I didnt see this version in readme or tag so i thought it didnt exist
