### ISSUE TITLE
How to sync server local timezone with this image?

### ISSUE THREAD

**Issue by felipekm** [mhart/alpine-node#127]
Hi have the following `Dockerfile` and I'd like to copy my localserver timezone to this image

```
FROM mhart/alpine-node:8.5

# App directory
WORKDIR /app
VOLUME /usr/www/app

EXPOSE 5000
CMD [ "npm", "start" ]
```

How can I achieve that?

**Comment by LoicMahieu** [comment]
Not sure but timezone is simply set by the `TZ` env variable.
You could accept an build arg and set the env variable in the image.

Should looks like (not tested):
```
FROM mhart/alpine-node:8.5
ARG TZ="Europe/Brussels" # default 🇧🇪 👍
ENV TZ=$TZ
# ...
```
```
docker build -t love_belgium --build-arg TZ=$TZ .
```

**Comment by felipekm** [comment]
I've tried it before without success.
Thanks @LoicMahieu 🇭🇷👍

**Comment by mhart** [comment]
Sorry @felipekm – this is a question better directed at either a Docker or Alpine forum – it's not specific to this Node.js image, and I'm not sure what the answer is.
