### ISSUE TITLE
Is it possible to use it on public hosting?

### ISSUE THREAD

**Issue by Molnfront** [mhart/alpine-node#13]
Can this docker image be used in for example Google Container Engine, BlueMix or AWS?
I will try to avoid using Ubuntu or Debian. CoreOS is an option on GCE.

**Comment by mhart** [comment]
You should be able to use this image anywhere – although it will be more work in a Kubernetes-like environment (which I think GCE is, but AWS isn't) – you can read more about the issues involved (and some solutions) here: https://github.com/gliderlabs/docker-alpine/issues/8#issuecomment-125768142

**Comment by Molnfront** [comment]
Ok! Thanks for the info.

**Comment by mhart** [comment]
(added a Caveats section to the README documenting this a little better)
