### ISSUE TITLE
Smaller image size?

### ISSUE THREAD

**Issue by styfle** [mhart/alpine-node#133]
There's a new project trending today called [scratch-node](https://github.com/astefanutti/scratch-node).

When I compared images for version `10.13.0`, scratch-node is smaller than alpine-node.

- `mhart/alpine-node:base-10.13.0` 17 MB
- `astefanutti/scratch-node:10.13.0` 14 MB

Is there some cruft that alpine-node (base images) could drop?

**Comment by mhart** [comment]
I don't think so – those images have nothing else AFAICT – so you can't install any alpine packages on them or anything else – without writing your own custom dockerfile. Nice idea! But quite a bit more restrictive than these images

**Comment by mhart** [comment]
Also, using `upx` is going to definitely affect the startup time of the binary (although I'd be intrigued to see by how much)
