### ISSUE TITLE
Dockerfile build error

### ISSUE THREAD

**Issue by doccker** [mhart/alpine-node#136]
branch master Dockerfile build 
node ok
npm error
yarn error

**Comment by mhart** [comment]
master is currently pointing to a `base` build, which doesn't have npm or yarn: https://github.com/mhart/alpine-node/commit/6c725b991c5d4ff492acb0192b60cd95354624d4

Checkout one of the non-base tags if you want to build with npm+yarn, eg: https://github.com/mhart/alpine-node/tree/11.8.0
