### ISSUE TITLE
RPS is very slow

### ISSUE THREAD

**Issue by dalisoft** [mhart/alpine-node#142]
Hello @mhart.
I played with `alpine-node` and works very well, fast and stable.
But there one issue, it's maybe Docker issue. I just ask for help.

Tested on different device, but RPS (Request/sec) is very different

Real Linux:
OS: Ubuntu 16.04 GNOME 
CPU: i3 2-core 2-thread 2Ghz
RAM: 2 GiB
RPS: ~15.000

Docker:
OS: Alpine Node (both Slim and Alpine)
CPU: i5 2-core 2-thread 2.5Ghz (configured within Docker Desktop)
RAM: 2 GiB
RPS: ~2.000

Docker:
OS: Node (v12.4)
CPU: i5 2-core 2-thread 2.5Ghz (configured within Docker Desktop)
RAM: 2 GiB
RPS: ~2.500

Reproducible repo: https://github.com/dalisoft/docker-fullstack-app-multistage-demo

There any recommendation and/or tweaks can be applied?

Any help would be appreciated!

**Note**: This is not an issue of `alpine-node`, an Docker issue, which is unacceptable for me, because 15x loss of performance, it's not worth of compatibility, i will spent 4-5 hour to configure Node.js rather than configuring Docker on server and performance will be much faster, an 15x, it's not a small numbers

**Comment by mhart** [comment]
How does it perform with a non-Alpine docker image?

**Comment by dalisoft** [comment]
I did not tested, as non-alpine image costs at 500Mb which is unacceptable for me at reason of internet connection (my connection is slow and limited). 
Plus, some bad guides, forced me reset Docker, said, performance will be better, sadly, does not improved performance.

**Comment by mhart** [comment]
Right, but I mean you should at least test it so that you can see if it's Alpine-specific, or just Docker in general.

**Comment by dalisoft** [comment]
Thanks. Ok, i try to test. Until it we can close this issue, as this is not confirmed issue

**Comment by dalisoft** [comment]
It's an Docker issue, not `alpine-node` issue, i updated OP
