### ISSUE TITLE
CDN Issue?

### ISSUE THREAD

**Issue by nazimjamil** [mhart/alpine-node#146]
Hi team, I'm seeing this issue when trying to build an image with `alpine-node:8` or above.

`docker build` seem fine, but then throws the following after this `RUN apk add --update git`:
```
fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/APKINDEX.tar.gz
ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.7/main: DNS lookup error
WARNING: Ignoring APKINDEX.70c88391.tar.gz: No such file or directory
fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/community/x86_64/APKINDEX.tar.gz
  git (missing):
    required by: world[git]
ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.7/community: DNS lookup error
WARNING: Ignoring APKINDEX.5022a8a2.tar.gz: No such file or directory
ERROR: unsatisfiable constraints:
```

When trying to reach that url in a browser, Chrome warns me that it is insecure (due to http). Trying to load the url with `https` shows that there's an error with the fastly cert.

Am I the only one experiencing this, or is there a problem with the CDN right now?

**Comment by nazimjamil** [comment]
Ah - never mind. Seems that there is a proxy effecting me at the office.

**Comment by conclusionlogic** [comment]
@nazimjamil did you find a workaround to this issue tho?
