### ISSUE TITLE
Only pulling Alpine 4.9 not 4.10

### ISSUE THREAD

**Issue by JFossey** [mhart/alpine-node#148]
I am using **mhart/alpine-node:12** as my base image in a project. When I look at the source code in this project it looks like it uses `alpine:3.10` as a the base image, but when I do a pull or build I get **4.9**.

## Action

In Dockerfile: `FROM mhart/alpine-node:12`

## Expected result

Alipine version 4.10 as based image.

## Result

```
$ cat /etc/alpine-release
3.9.4
```

**Comment by mhart** [comment]
`mhart/alpine-node:12` uses alpine 3.9. See https://github.com/mhart/alpine-node/commit/b970f42158026b842019d9c25310663ffb908b6b

This was the latest version when Node.js 12.x was initially released. To prevent breaking changes to ppl's apps, I don't change the OS when upgrading Node.js.
