### ISSUE TITLE
System error: no such file or directory

### ISSUE THREAD

**Issue by arnaudsj** [mhart/alpine-node#15]
Hi,

Running into this weird error on ubuntu 14.04 with docker installed properly via docker.io's method.

Any ideas?

```
$ sudo docker run -it mhart/alpine-node:latest /bin/sh
no such file or directory
Error response from daemon: Cannot start container 1644f323eeb4695d64919ec564ee14484ed58e1573ece583226de4dccfdebdc3: [8] System error: no such file or directory
```

FYI, this works fine on my local docker instance on OS X... so I am kind of confused here as of what is missing.

Thank you!

**Comment by mhart** [comment]
@arnaudsj is this still an issue? I haven't run into this before – it sounds like it would be more to do with your docker setup than anything to do with the image

**Comment by mhart** [comment]
Pretty sure this is a Docker setup issue. Going to close, but if you can reproduce, happy to reopen
