### ISSUE TITLE
Newest version 14 image size

### ISSUE THREAD

**Issue by kevinsimper** [mhart/alpine-node#151]
Hi! Thanks for all the hard work!

I use the image and could not understand why 14 was sustainally bigger in size compared to previous versions.

That lead me down to https://github.com/nodejs/node/issues/6860 which then lead me to understand ICU.

14 now includes full-icu compared to before where small-icu was included only.

I am split between whether i want to have the full icu included in my small apps or not. Consistentsy is key, but the new image is much bigger.

**Comment by mhart** [comment]
You can exclude it if you like by compiling your own build, but I'm unlikely to include a separate version anytime soon given the overhead maintenance of it

**Comment by kevinsimper** [comment]
Make sense, it was also to notify other people looking into this 👍

It is a big chance going from 42 mb to 73 mb is a 73 % increase in size.
