### ISSUE TITLE
Node version change?

### ISSUE THREAD

**Issue by appetize-api** [mhart/alpine-node#152]
Hi there,

Been using mhart/alpine-node:10 in an internal pipeline and we started getting an error that this image now has node 10.22.

We were expecting 10.21.  Did that change or am I looking at this wrong?

If that's the case, should I be using an official node image instead?  Can someone chime in, please?

Thanks in advance.

**Comment by mhart** [comment]
Sorry what do you mean you got an error?

**Comment by appetize-api** [comment]
we have a project that is expecting engine "<=10.21.0".  And this week it started acting out.

**Comment by mhart** [comment]
If you want to use `10.21` and only `10.21` then use `mhart/alpine-node:10.21`

**Comment by appetize-api** [comment]
`The engine "node" is incompatible with this module. Expected version ">=10.12.0 <=10.21.0". Got "10.22.0"`

**Comment by appetize-api** [comment]
I see.. so the tag `10` changes.. like a `^10`... yes.. that'd explain it... thanks!

**Comment by mhart** [comment]
That's a super weird requirement for a project (because minor versions are backwards compatible). But if you have to stick to it, then specify it explicitly

**Comment by appetize-api** [comment]
Yup.... it is...

**Comment by mhart** [comment]
Cool, closing 👍
