### ISSUE TITLE
ARM version

### ISSUE THREAD

**Issue by npenin** [mhart/alpine-node#154]
Hi,

I know this has already been discussed in #64 , but since the introduction of buildx, I can see it could be easy to build an ARM version. I have already cloned the project to try it on my machine. However, I am not sure how the shell scripts are working: build.sh is able to make a build for both arm64 and amd64, but then if I try the build-tools, it is complaining that the image does not exist on docker.io. Could you provide a little help here or even just enable multi-platform on your images ?

Thanks

**Comment by mhart** [comment]
You shouldn't need to do build-tools – that's only for updating npm/yarn. build.sh (and build-slim.sh) should be all you need.

**Comment by npenin** [comment]
I actually noticed that now official nodejs images are provided with alpine.
