### ISSUE TITLE
Failing to build Dockerfile

### ISSUE THREAD

**Issue by lackerman** [mhart/alpine-node#16]
Hi Michael, not sure if I'm missing something but when I try and build the image using your Dockerfile I get the following error:

``` shell
/usr/lib/gcc/x86_64-alpine-linux-musl/4.9.2/../../../../x86_64-alpine-linux-musl/bin/ld.gold: fatal error: /node-v4.2.4/out/Release/mksnapshot: Not supported
collect2: error: ld returned 1 exit status
deps/v8/tools/gyp/mksnapshot.target.mk:139: recipe for target '/node-v4.2.4/out/Release/mksnapshot' failed
make[1]: Leaving directory '/node-v4.2.4/out'
make[1]: *** [/node-v4.2.4/out/Release/mksnapshot] Error 1
Makefile:45: recipe for target 'node' failed
make: *** [node] Error 2
```

Building on an Ubuntu 14.04 VM.

Any ideas?

**Comment by mhart** [comment]
Hmmm, no idea unfortunately! I build it on my Mac, running docker-machine w/ VirtualBox.

If you remove `binutils-gold` from the `apk` steps then I think that error should go away for you – but I needed to add that for Node v5 support, and I think it's still required for that.

If you figure out what the exact issue is – and you manage to build v5 on your architecture, let me know!

**Comment by lackerman** [comment]
I managed to get `4.2.3` to build but `4.2.4` failed after removing `binutils-gold` with the following error:
`collect2: fatal error: cannot find 'ld'`

**Comment by mhart** [comment]
Ah, might just need to include `binutils` then.

Is there a reason you can't build using the image in the Docker hub as a base?

**Comment by lackerman** [comment]
I want to use the same tooling to install certs and phantomjs, instead of increasing the number of layers.

**Comment by mhart** [comment]
Ok, gotcha.

If it's size you're worried about you could always just build then run a container and `docker export <container_id> | docker import -` – that'll flatten all the layers.

Have you figured out which step it's failing on? I wonder if changing the build steps to something like this would work (and keeping `binutils-gold`):

```
  ./configure --prefix=/usr ${CONFIG_FLAGS} && \
  NPROC=$(grep -c ^processor /proc/cpuinfo 2>/dev/null || 1) && \
  make out/Makefile && \
  make -j${NPROC} -C out mksnapshot && \
  paxctl -cm out/Release/mksnapshot && \
  make -j${NPROC} && \
  make install && \
  paxctl -cm /usr/bin/node && \
```

The other option to try is adding `--without-snapshot` to the `./configure` line – the problem with this is that it disables the snapshotting feature of v8 which allows a faster startup.

If either of those work, let me know and I'll update the Dockerfile.

**Comment by mhart** [comment]
Out of interest, what's the underlying architecture that you're building on? ie, what's the VM running on?

**Comment by lackerman** [comment]
Ok, I found success by running `./configure` with the `--without-snapshot`

But no luck using the first set of steps, I get the following error
`make: *** No rule to make target 'mksnapshot'.  Stop.`

**Comment by lackerman** [comment]
1. Mac Yosemite with the docker toolset installed & 
2. Ubuntu 14.04 x86_64 VM running through Virtuabox on Windows 7

**Comment by mhart** [comment]
@lackerman so strange that I don't get the same issue on my Mac. Well, you can run it without the snapshot if you like – it just won't take advantage of v8's snapshotting feature.

Out of interest, do the built images from https://hub.docker.com/r/mhart/alpine-node/ work fine on your architecture? I don't really want to remove the `--without-snapshot` setting if it's still building fine in my environment.

**Comment by lackerman** [comment]
All v4 images I've used from DockerHub work just fine. I'm with you on not adding `--without-snapshot`. What concerns me is that we're experiencing different build behaviour on the same architecture and that sounds like it could potentially be a bug - but tracking down where, is the real issue. I'll keep trying and let you know if I find anything.

**Comment by mhart** [comment]
Ok cool – thanks @lackerman ! Definitely puzzling.

**Comment by lackerman** [comment]
Ok, I'm not sure what going on. I went back to the `4.2.4` tag, ran docker build and it worked just fine.

Yesterday I was getting very slow downloads from the alpine repo, perhaps files were getting corrupted. I'm not sure. I've build 4.2.4 twice, once using npm version 2 and once using npm version 3 and on both occasions it was successful. Apologies for the time wasting I guess.

**Comment by lackerman** [comment]
Btw, gr8 work on the project!

**Comment by mhart** [comment]
No problem! TBH it may be a weird Docker heisenbug – there seem to be a lot of those... Esp w/ npm v3

**Comment by mhart** [comment]
Btw, I recently ran into this with Docker Automated Builds and even `--without-snapshot` didn't make a difference. In the end I had to resort to this: https://github.com/mhart/alpine-node/commit/c0f3a406568524340bc1bab34d390cff7172ee6d – this may solve your issues too.
