### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by celayale** [mhart/alpine-node#164]
The most recent mhart/alpine-node image is based on node 16.4, while the latest node 16 version at this point is 16.14

Is there any plan to keep publishing newer node 16.x images?

**Comment by maartenkools** [comment]
@celayale Consider using the [official node image](https://hub.docker.com/_/node), which is based on Alpine as well. Looks like not much is happening with this project.

**Comment by celayale** [comment]
Yep, that's most probably what we are going to do 🙂
