### ISSUE TITLE
Dynamic Symbol Retrieval Error: Symbol not found: errno

### ISSUE THREAD

**Issue by pkoretic** [mhart/alpine-node#17]
using net-keepalive module that used node-ffi https://www.npmjs.com/package/net-keepalive
throws this error:

```
Dynamic Symbol Retrieval Error: Symbol not found: errno
```

judging from the quick google search it seems that is something regarding libc  
some solutions involve setting correct path or maybe is something regarding musl?

**Comment by mhart** [comment]
I'd say the latter. I'd say it's something to do with node-ffi not working with the musl implementation.

It might be worth raising an issue at https://github.com/node-ffi/node-ffi to see if they can add support for musl-based systems, like Alpine Linux.

**Comment by mhart** [comment]
Opened an issue over here: https://github.com/node-ffi/node-ffi/issues/273

**Comment by mhart** [comment]
(closing this as it's not directly related to this Docker image – will reopen if it's somehow related though).
