### ISSUE TITLE
Move to alpine:latest

### ISSUE THREAD

**Issue by bobelev** [mhart/alpine-node#19]
Latest alpine linux image is 3.3. They are pretty the same but in 3.3 new community repo was introduced. It is very helpful in custom builds. 
It would be great to have latest base image for nodejs apps.

**Comment by mhart** [comment]
Dupe of https://github.com/mhart/alpine-node/pull/18 – now that they've pushed 3.3.1 (just yesterday) I'll use it for the next 5.x build.

**Comment by mhart** [comment]
Node.js just released v5.5.0 so the latest Dockerfile uses 3.3
