### ISSUE TITLE
Question about nodejs compilation

### ISSUE THREAD

**Issue by rgarrigue** [mhart/alpine-node#21]
Hi

I took inspiration from your work to make my own alpine-nodejs +stuff Dockerfile. I got a puzzling issue : everything is building fine on my centos's VM but pushing to the public registry I end up with

```
collect2: error: ld returned 1 exit status [0mdeps/v8/tools/gyp/mksnapshot.target.mk:139: recipe for target '/node-v5.6.0/out/Release/mksnapshot' failed [91mmake[1]: *** [/node-v5.6.0/out/Release/mksnapshot] Error 1 [0mmake[1]: Leaving directory '/node-v5.6.0/out' Makefile:45: recipe for target 'node' failed
```

Does that ring a bell to you by any chance?

Best regards,

**Comment by mhart** [comment]
@rgarrigue not really – although I'm not really sure what you mean when you say that error occurred when you pushed to the public registry?

**Comment by mhart** [comment]
Going to close this, doesn't seem to be an issue with this repo

**Comment by rgarrigue** [comment]
Hi Michael

Sorry for the late reply. True it isn't about your repo. I'm trying to use
piece of your work to provide some alpine+node+other Dockerfile. Which work
fine if I `docker build` on my own server. I plugged my github stuff to
hub.docker.com and I end up with [this error](https://hub.docker.com/r/rgarrigue/thelounge/builds/bajfzo2amc4zxvaht9dzsqa/)

> g++ -pthread -rdynamic -m64 -fuse-ld=gold
> -B/node-v5.7.1/third_party/binutils/Linux_x64/Release/bin -m64 -o
> /node-v5.7.1/out/Release/mksnapshot -Wl,--start-group
> /node-v5.7.1/out/Release/obj.target/mksnapshot/deps/v8/src/snapshot/mksnapshot.o
> /node-v5.7.1/out/Release/obj.target/deps/v8/tools/gyp/libv8_base.a
> /node-v5.7.1/out/Release/obj.target/deps/v8/tools/gyp/libv8_nosnapshot.a
> /node-v5.7.1/out/Release/obj.target/deps/v8/tools/gyp/libv8_libplatform.a
> /node-v5.7.1/out/Release/obj.target/deps/v8/tools/gyp/libv8_libbase.a
> -Wl,--end-group -ldl -lrt
> [91m/usr/lib/gcc/x86_64-alpine-linux-musl/5.3.0/../../../../x86_64-alpine-linux-musl/bin/ld.gold:
> fatal error: /node-v5.7.1/out/Release/mksnapshot: Not supported collect2:
> error: ld returned 1 exit status make[1]: ***
> [/node-v5.7.1/out/Release/mksnapshot] Error 1 [0mdeps/v8/tools/gyp/
> mksnapshot.target.mk:139: recipe for target
> '/node-v5.7.1/out/Release/mksnapshot' failed

That driving me nutty, the last build is a copy/paste of your Dockerfile,
and I still got the issue. Can you tell me what I'm doing wrong if you got
an idea ?

Thanks & regards

**Comment by mhart** [comment]
Only thing I can suggest is to try passing `--without-snapshot` to the `configure` command and see if that helps.

**Comment by rgarrigue** [comment]
Okay. I do owe you a beer at least, that did the trick.

**Comment by mhart** [comment]
Glad to hear it! :+1:

**Comment by mhart** [comment]
Btw, I recently ran into this with Docker Automated Builds and even `--without-snapshot` didn't make a difference. In the end I had to resort to this: https://github.com/mhart/alpine-node/commit/c0f3a406568524340bc1bab34d390cff7172ee6d – this may solve your issue too.
