### ISSUE TITLE
rebuild with updated base image

### ISSUE THREAD

**Issue by ncopa** [mhart/alpine-node#23]
Current image has broken openssl. It would be nice to have it rebuilt with the updated/fixed alpine images ASAP.

(They should also have a significantly faster default mirror)

**Comment by mhart** [comment]
Was just going to wait for the latest Node.js releases before doing this – this image doesn't use openssl as a shared library either, so I'm not sure it would help much?

**Comment by ncopa** [comment]
apk is linked to libcrypto so openssl is there.

**Comment by mhart** [comment]
@ncopa yeah, that's true – but I guess it would only affect ppl who have specifically linked against it, like in a native module?

In any case, latest Node.js versions are out now so the images have been updated. Thanks!
