### ISSUE TITLE
Updating npm in 5.9 to allow production installs

### ISSUE THREAD

**Issue by corbinu** [mhart/alpine-node#26]
So I ran into this issue https://github.com/npm/npm/issues/11699 in version 5.8 and 5.9 of the container as node is still packaging npm 3.8.0 and this was fixed in 3.8.1.

Obviously I when I tried to update npm I ran into https://github.com/npm/npm/issues/9863

However when I tried the solution there I could not install fs-extra into the npm directory due to
https://github.com/npm/npm/issues/10686

So I finally came up with this line in my Dockerfile to update npm thought you might be interested in integrating it in to this container

```
npm install fs-extra \
    && cp -r node_modules/* /usr/lib/node_modules/npm/node_modules \
    && sed -i s/graceful-fs/fs-extra/g /usr/lib/node_modules/npm/lib/utils/rename.js \
    && sed -i s/fs.rename/fs.move/g /usr/lib/node_modules/npm/lib/utils/rename.js \
    && rm -rf node_modules \
    && npm install -g npm@latest
```

**Comment by mhart** [comment]
v5.9.0 of this container comes with npm 3.8.1 so I don't think this should be a problem?

**Comment by corbinu** [comment]
Oh maybe docker didn't actually pull the new container. Either way at least in my case I like to be on latest for these kind of issues, but I can always just do the update at the start of my container.

Thanks!

**Comment by mhart** [comment]
Yeah, I'd prefer not to mess with the files of the globally installed npm in ppl's containers. Obviously I'd love to see https://github.com/npm/npm/issues/9863 fixed, but I'm not sure this is a good idea for everyone.

Glad to know it's a relatively simple fix for people though! Hopefully if someone wants to do the same thing they'll stumble on this issue.

**Comment by frank-dspeed** [comment]
```
RUN cd $(npm root -g)/npm \
 && npm install fs-extra \
 && sed -i -e s/graceful-fs/fs-extra/ -e s/fs\.move/fs.rename/ ./lib/utils/rename.js
```

**Comment by corbinu** [comment]
@frank-dspeed 

Not sure what the point of your comment was as that command does not work in this container. Can you give a little more context please?
