### ISSUE TITLE
node-gyp needs build tools

### ISSUE THREAD

**Issue by tino** [mhart/alpine-node#27]
node-gyp, which is often used by packages installed through npm (at least that is my experience), needs `python`, `make`, and `gcc`. Would it make sense _not_ to clean those up? (Currently happening in line 36 of the Dockerfile)

**Comment by mhart** [comment]
The idea of this docker image is to be as small as possible with a full node installation – for ppl who don't have native dependencies, it would add a lot of weight to include these.

There's an example on the README for how to add them in your own Dockerfile if you need them for your project though: https://github.com/mhart/alpine-node#example-dockerfile-for-your-own-nodejs-project

**Comment by cusxio** [comment]
@mhart I'm fairly new to this, so I was wondering what is the purpose of installing `make gcc g++ python linux-headers paxctl gnupg` and removing them later?

In the [official dockerfile](https://github.com/nodejs/docker-node/blob/cbdacad677bafa044140610f851bed00254de1ca/5.11/Dockerfile) it does not seem like Node requires it for installation.

**Comment by mhart** [comment]
That Dockerfile doesn't need any build tools because it's not actually building node – it's just unpacking a prebuilt binary on debian. There's no prebuilt binary for Alpine, so we have to build it ourselves – hence all the build tools that need installing. They're then removed to keep the image size down – most ppl won't need them again – but if you do you can always reinstall them

**Comment by Nepoxx** [comment]
Sorry about posting on an old thread, but since Google lands here for this question, I'dd suggest doing the following if you have native dependencies:

```
RUN apk add --no-cache make gcc g++ python && \
  npm install --production --silent && \
  apk del make gcc g++ python
```

This way the build dependencies don't end up in your Docker layers and thus keep the image size almost as small as if you didn't install those dependencies.

**Comment by JorritPosthuma** [comment]
Old thread, but because of google, still relevant :).
To make it even simpler you can do:

```
RUN apk add --no-cache --virtual .build-deps make gcc g++ python \
 && npm install --production --silent \
 && apk del .build-deps
```
Or simpler, by using `alpine-sdk`, similar to Ubuntu's `build-essential`:
```
RUN apk add --no-cache --virtual .build-deps alpine-sdk python \
 && npm install --production --silent \
 && apk del .build-deps
```

**Comment by AkashBabu** [comment]
Perhaps you could use docker multi-stage build and copy `node_modules` from ubuntu image and then run `npm rebuild` in alpine image.

Sample Dockerfile:
```Dockerfile
# Stage-1 dependencies
FROM node:latest as dep

RUN mkdir /sample
WORKDIR /sample

ADD package.json .
RUN ["npm", "i", "--only=production"]


# Stage-2 final image
FROM node:alpine

RUN mkdir /sample
WORKDIR /sample

COPY --from=dep /sample/node_modules ./node_modules
RUN ["npm", "rebuild", "-q"]

ADD . .

ENTRYPOINT [ "npm", "start" ]
```

Hope this helps

**Comment by thebetterjort** [comment]
@AkashBabu Is the prefered way of handling deps moving forward.

**Comment by AkashBabu** [comment]
@thebetterjort Can you please elaborate your statement?

**Comment by thebetterjort** [comment]
@AkashBabu 
If you need to add build-essential / alpine-sdk then you shouldn't be using node alpine. But, luckily Docker gives us multistage builds.
" With a statically compiled language like Golang people tended to derive their Dockerfiles from the Golang "SDK" image, add source, do a build then push it to the Docker Hub. Unfortunately the size of the resulting image was quite large - at least 670mb.

A workaround which is informally called the _builder pattern_ involves using two Docker images - one to perform a build and another to ship the results of the first build without the penalty of the build-chain and tooling in the first image.

Multi-stage builds give the benefits of the _builder pattern_ without the hassle of maintaining three separate files:

The prefered way of handling deps for the future of containers is multistage as it miitigates multiple Dockerfiles for different architectures."

https://github.com/moby/moby/pull/32063

**Comment by mhart** [comment]
@thebetterjort @AkashBabu there's already an example of doing multistage builds in the README: https://github.com/mhart/alpine-node#example-dockerfile-for-your-own-nodejs-project (the second example)

**Comment by AkashBabu** [comment]
+1 for @mhart's answer

**Comment by Startouf** [comment]
Just a note for people still referring to this thread : 

> `RUN apk add --no-cache --virtual .build-deps alpine-sdk python`

May throw some error

> [ 5/17] RUN apk add --no-cache alpine-sdk python:
#9 0.234 fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/main/x86_64/APKINDEX.tar.gz
#9 0.337 fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/community/x86_64/APKINDEX.tar.gz
#9 0.592 ERROR: unable to select packages:
#9 0.640   python (no such package):

You have to specify the python version in some cases to avoid apk errors
```
RUN apk add --no-cache --virtual .build-deps alpine-sdk python2
```
or
```
RUN apk add --no-cache --virtual .build-deps alpine-sdk python3
```

**Comment by ndj91** [comment]
Anyone still having issue.

You must now specify the python version e.g. `python2`

Found it here https://stackoverflow.com/questions/62169568/docker-alpine-linux-python-missing
