### ISSUE TITLE
Question: How can you get into the running docker container?

### ISSUE THREAD

**Issue by robertd** [mhart/alpine-node#28]
```
$ docker exec -it node-app-1 /bin/bash
exec: "bash": executable file not found in $PATH
```

Is there another way one can get in the running alpine-node based container?

**Comment by mhart** [comment]
Yes – `/bin/bash` doesn't exist on Alpine (unless you manually install it). `/bin/sh` and `/bin/ash` do though.

Try `docker exec -it node-app-1 sh`

**Comment by robertd** [comment]
Thank you! :smile:

**Comment by pedroobando** [comment]
Thank you men...

**Comment by mxlydx** [comment]
thks man

**Comment by 1992clement** [comment]
alleluja

**Comment by diegochiquero** [comment]
Thanks a lot!!!

**Comment by dingcang** [comment]
```shell
cat /etc/shells
```
you can see sh and ash only

**Comment by ankitjena** [comment]
Thanks :)))

**Comment by jomoflash** [comment]
Thanks for this Info

**Comment by marlonklc** [comment]
thanks a lot ! Fast answer 😂

**Comment by hros19** [comment]
Thank you so much!
