### ISSUE TITLE
Wouldn't it better to use and maintain Alpine packages?

### ISSUE THREAD

**Issue by frol** [mhart/alpine-node#3]
I've updated `iojs` package yesterday (pull-requested and it is already in `testing` repo) and `nodejs` package can be updated as well. However, I'm not in nodejs/iojs development, I just wanted to play with it, so I won't be able to maintain those packages.

Wouldn't you volunteer to maintain iojs and, possibly, nodejs packages?

**Comment by mhart** [comment]
That's not really where my interest lies – I'm looking to make a very small Node.js/iojs Docker image – the smallest possible really.

Probably best to contact the maintainers of those packages on Alpine, or perhaps see if the NodeSource people want to add Alpine [to their repetoire](https://github.com/nodesource/distributions)
