### ISSUE TITLE
Can't resolve linked containers on Docker Cloud

### ISSUE THREAD

**Issue by evanp** [mhart/alpine-node#30]
[Docker Cloud](https://cloud.docker.com/) uses DNS rather than modifications to /etc/hosts to enable lookup between linked containers. Unfortunately, it triggers the same errors with musl that occur with Kubernetes (I think).

I realize this is an upstream problem; I figured I'd add an issue here so people would know where to find it. It might be worthwhile to mention in the README, like the Kubernetes issue.

Example file attached. Supposedly "alpine:edge" works correctly, so I'm going to see if I can build alpine-node with the edge tag instead of 3.3.

[testalpine.yml.txt](https://github.com/mhart/alpine-node/files/202884/testalpine.yml.txt)

**Comment by mhart** [comment]
Yeah, I believe this is all covered in the issue linked to on the README (and the various discussions available from there) – it's not just Kubernetes specific, but about the musl's DNS behaviour in general.

musl-libc 1.1.13 has these changes, which are in alpine:edge – once they become stable branch I'll update this repo
