### ISSUE TITLE
why build from scratch when Alpine repo has nodejs4.3 package?

### ISSUE THREAD

**Issue by streamnsight** [mhart/alpine-node#32]
any reason not to use the official package?

https://pkgs.alpinelinux.org/packages?name=nodejs&branch=v3.3&repo=&arch=x86_64&maintainer=

**Comment by mhart** [comment]
@streamnsight in general, no – they seem to do a pretty good job at maintaining that package.

But they're not always up to date with the latest versions of each release (ie, currently v5.10.1, v4.4.3, v0.12.13, v0.10.44)
