### ISSUE TITLE
Use Docker Automated Builds

### ISSUE THREAD

**Issue by numbnut** [mhart/alpine-node#33]
Hi,
thanks for the great alpine based node image. Would you mind to use docker automated builds for your images to make the integrity verifiable? That would be really nice. If you don't want to, I would fork the project and do it on my own. I just wanted to let you know and choose your way to do it.

**Comment by mhart** [comment]
I looked at this a while back but it didn't seem to have support for the various ways I tag the repo. I've just looked again now and I think it should support everything, so I'm going to give it a shot over at https://hub.docker.com/r/mhart/alpine-node-auto (attempting a build as we speak)

I'm not sure if a docker repo can be an automated build at the same time as supporting manual pushes, so I'm not entirely sure what to do with https://hub.docker.com/r/mhart/alpine-node going forward if this proves successful

I'll leave this issue open as I get some more experience with automated builds and whether they're a good fit going forward. Unless there proves to be any reason not to, `mhart/alpine-node-auto` should be able to continue to exist going forward, regardless of whether `mhart/alpine-node` switches to automated builds or not, so you should at least be able to try it out (assuming this build completes... the logs are empty at the moment)

**Comment by mhart** [comment]
Alrighty, after lots of fiddling, and some [nasty hacks](https://github.com/mhart/alpine-node/commit/c0f3a406568524340bc1bab34d390cff7172ee6d), I've managed to get automated builds working over at https://hub.docker.com/r/mhart/alpine-node-auto.

There are a number of issues that currently prevent me from making this the default however – one is that it doesn't seem to manage more than 3 git tags being pushed at once – as soon as I push more than 3 git tags, it doesn't pick them up and queue builds for them. The other issue is that it takes _a long_ time to build – like, I'm talking orders of magnitude longer than locally – around an hour for v4/v5/v6

Closing this issue for now – but feel free to keep commenting here if you have any more questions/suggestions.

**Comment by mhart** [comment]
Bleh. Docker Hub also doesn't seem to pick up that certain tags point to the same git commit (eg, `0.12` and `0.12.14`) – and it unnecessarily builds them separately. I suspect it's going to take many many hours before all the current versions are built.

![screen shot 2016-05-08 at 11 46 09 am](https://cloud.githubusercontent.com/assets/367936/15098754/95610cac-1512-11e6-9da4-ca89eb40f3ea.png)
