### ISSUE TITLE
Add alpine:edge tag 

### ISSUE THREAD

**Issue by PuKoren** [mhart/alpine-node#34]
Heya!

It would be great to have the edge base alpine tag to chose from this repo tags so we can get the latest  Alpine (we need some fixes from 3.4 here, not yet published but in edge)

**Comment by mhart** [comment]
Interesting idea – I'm not sure how I'd align it with the Node.js tags though, it would essentially double the amount of tags needed. Any thoughts on this?

**Comment by PuKoren** [comment]
I have no good idea about this yet. The only thing I've been thinking would be a tag like `mhart/alpine-node:edge` that would be based on alpine:edge and compile nodejs using nightly builds, so a 'full edge' tag for experimental use only. Not sure if this is a good idea.

For info, docker-alpine should release the 3.4 in a 2 week window (this will solve compatibility issue with Kubernetes and Docker Cloud)

**Comment by mhart** [comment]
Yeah, looking forward to 3.4 coming out – hopefully there's no breaking changes and I'll just be able to update all the images with the next Node.js release

**Comment by nVitius** [comment]
Alpine 3.4 was released a couple days ago and the image was tagged today. @mhart

**Comment by mhart** [comment]
Yep! Scan is still in progress: https://hub.docker.com/r/library/alpine/tags/

**Comment by mhart** [comment]
Ok, I think that scan is stuck, the image seems to be fine.

I've pushed the latest Node.js, v6.2.1, with Alpine 3.4 – so I'm gonna close this.

If no issues come through with compatibility, etc, then I'll update the other tags (v5, v4, v0.12 and v0.10) to Alpine 3.4 next time there's a release of them.
