### ISSUE TITLE
Cannot connect to external MongoDB host 

### ISSUE THREAD

**Issue by ChetanBhasin** [mhart/alpine-node#38]
Node is unable to connect to a MongoDB instance hosted outside the image.

NPM package `mongoose` is being used to connect to the database. Given the IP address and port (unchanged) of the MongoDB, the code works just fine without making a change if we use `node:latest` image from Dockerhub.

Could this be because outbound communication is blocked?

**Comment by mudrii** [comment]
did you open the ports or use compose to set in same network

**Comment by ChetanBhasin** [comment]
@mudrii The ports were exposed and this was run on Kubernetes.

**Comment by mhart** [comment]
@ChetanBhasin unless you build your own image with `alpine:edge` you'll have problems on Kubernetes with DNS – you can see more about this in the README: https://github.com/mhart/alpine-node#caveats

**Comment by skcc75** [comment]
@mhart having the same issue with Bluemix IBM Containers.  still need to build own image with `alpine:edge`?

**Comment by mhart** [comment]
@kyrylkov a lot of dns issues were resolved with Alpine 3.4 – which these docker images have been using for a while now.

Which tag are you using? Does it work when you try running it all locally?

**Comment by skcc75** [comment]
@mhart  Tried both `6` and `base-6`.  I'll try locally.

**Comment by skcc75** [comment]
@mhart Works fine locally

**Comment by mhart** [comment]
@kyrylkov and it works in Bluemix with a non-Alpine image (like `node:latest`)?

If so, is there any way you can distil something small and reproducible?

I'm not guaranteeing I'll be any help, especially if it's an Alpine issue, but I'm intrigued to see what the issue might be
