### ISSUE TITLE
Image size nearing 400MB (.nyc_output)

### ISSUE THREAD

**Issue by PuKoren** [mhart/alpine-node#39]
Hello!

I have an issue with the container, when I try to build it myself (I want to test it against alpine:edge).

I'm taking the current Dockerfile provided on this repo and do a `docker build -t mytag .`. But then my image size is 398.6 MB. Do you have any clue about this? Anything special to do?

Thanks

**Edit**: after investigation, folder `/usr/lib/node_modules/npm/.nyc_output` takes up to 330 MB. I added it to the final rm command. If usefull, I'm building on OSX using latest Docker for mac beta

**Comment by mhart** [comment]
@PuKoren I'm not sure why `nyc` is installing? Are you adding that yourself? I don't think it's part of the base installation

**Comment by PuKoren** [comment]
@mhart nop I just copy/pasted the Dockerfile from this repo and ran a build to test it. Using `VERSION=v6.2.0` `NPM_VERSION=3`.

That is very weird. From what I googled I see that nyc is used for tests reports? I wonder why npm have it... Still digging into the issue, will update this issue as I find more info

**Comment by mhart** [comment]
AFAICT that directory only appears if you run the `nyc` command – maybe it's being run during a test or something... Maybe another npm module is running it during installation? I certainly haven't seen it before

**Comment by mhart** [comment]
The only other thing I can think is that some npm module (maybe even npm itself?) has accidentally added that directory (or forgotten to include it) to their module and published it!

**Comment by mhart** [comment]
I just checked this myself and you're absolutely right – happens on my local machine (a Mac) too: https://github.com/npm/npm/issues/12873

**Comment by mhart** [comment]
@PuKoren have confirmed it's an issue with npm – the latest version (v3.9.3) is huge!

https://github.com/npm/npm/issues/12873#issuecomment-222149117

So don't worry, it's nothing you've done 😸  – you could manually install npm v3.9.2 if you want, or delete the nyc_output directory – or wait for the next npm version

**Comment by mhart** [comment]
(going to close this – nothing really we can do about it until npm update)

**Comment by mhart** [comment]
So it will be fixed in npm v3.9.5 by the looks of it
