### ISSUE TITLE
Why is there no 0.12.7 Tag?

### ISSUE THREAD

**Issue by erikmueller** [mhart/alpine-node#4]
Could be the case that I missed something but the Readme says that `alpine-node-base` has a 0.12.7 tag but it has not. 
What I noticed tho is that `latest` seems to give you `0.12.7`. Did the missing tag happen by mistake or by intend?

**Comment by mhart** [comment]
Hmmm, no idea – all three tags `latest`, `0.12` and `0.12.7` should point to the same image (`dfa6bb89b253`)

Can you check again now? I've just pushed them again to be sure.

**Comment by erikmueller** [comment]
Now it's there https://registry.hub.docker.com/u/mhart/alpine-node-base/tags/manage/ could have been a problem while pushing. Thanks a lot. Really love this small image.
