### ISSUE TITLE
Issue when Alpine is updated

### ISSUE THREAD

**Issue by leorossi** [mhart/alpine-node#40]
Hi!

I have just encountered this issue, since alpine linux was recently updated and you were so quick to update your image as well (great job, though! 👍 )

Some of the packages that I use in that image, are not present in alpine 3.4 so my build fails.
Is it possible to keep the "previous alpine" version up? So, in this case, it will be very useful to have a `alpine-node:base` with Alpine 3.3 and another with Alpine 3.4.

Thanks!

**Comment by mhart** [comment]
Oh no, that's unfortunate!

I think that's gonna be tricky to try and keep two copies of Alpine for each Node.js release – there's already so many tags to manage with this project.

Is it likely that those packages will be added sometime soon? If so it might be better to just hardcode your release at `mhart/alpine-node:base-6.2.0` until then (or use `mhart/alpine-node:base-5`)

**Comment by leorossi** [comment]
These are missing packages, for this particular image, as you can see are important PHP packages, so yes it is likely that those packages will be added soon

```
ERROR: unsatisfiable constraints:
  php-cli (missing):
    required by: world[php-cli]
  php-ctype (missing):
    required by: world[php-ctype]
  php-curl (missing):
    required by: world[php-curl]
  php-dom (missing):
    required by: world[php-dom]
  php-fpm (missing):
    required by: world[php-fpm]
  php-gd (missing):
    required by: world[php-gd]
  php-json (missing):
    required by: world[php-json]
  php-mcrypt (missing):
    required by: world[php-mcrypt]
  php-mysql (missing):
    required by: world[php-mysql]
  php-openssl (missing):
    required by: world[php-openssl]
  php-pdo_mysql (missing):
    required by: world[php-pdo_mysql]
  php-phar (missing):
    required by: world[php-phar]
  php-xml (missing):
    required by: world[php-xml]
  php-zlib (missing):
    required by: world[php-zlib]
```

I think that sticking with a version like `mhart/alpine-node:base-6.2.0` will be better for us as we are setting up continuous deploy etc... 👍

**Comment by mhart** [comment]
@leorossi yeah, I chose to update on v6.2.1 because it's not LTS yet, so it's still a bit of a moving target with lots of features still being added – I'll be a lot more careful with updating v4.x because v4.x is LTS – and same with v6.x in October when it goes LTS.

So if you want safety and you don't specifically need any features from Node v6.x, then I'd choose `mhart/alpine-node:base-4`

In any case, I guess once those packages are available you should be all fine – let me know when they are too!

**Comment by leorossi** [comment]
Yes we will wait for those packages to be ready and keep the most recente Node 6.x + Alpine 3.3 image, thanks for support!

**Comment by mhart** [comment]
@leorossi actually I've just checked and all these packages seem to exist, they've just been renamed to `php5`/`php5-*`

Under Alpine 3.3: http://git.alpinelinux.org/cgit/aports/tree/main/php/APKBUILD?h=3.3-stable

Under Alpine 3.4: http://git.alpinelinux.org/cgit/aports/tree/main/php5/APKBUILD?h=3.4-stable

Going to close this – but let me know if you run into any other issues

**Comment by leorossi** [comment]
Thanks @mhart we will point to those packages then!

**Comment by sgeorge** [comment]
Had the same problem, solved with "apk add --no-cache php7-fpm" inside the official alpine container
