### ISSUE TITLE
Add the image to quay.io

### ISSUE THREAD

**Issue by ifraixedes** [mhart/alpine-node#41]
I would like to know if you could consider to push this image to [quay.io](https://quay.io).

The reason is because is very good in terms of size and it'd very helpful to use it as a dependency for [abuild (App Standard Container tool)](https://github.com/appc/acbuild).

acbuild can use dependencies hosted under a domain (e.g example.com/nick/image), however as far as I know isn't possible to se docker images hosted in hub.docker.io as a dependency, but quay.io offer that making an APC image usable with [rkt](https://coreos.com/rkt/docs/latest/).

An example of an quay.io image can be used in acbuild is https://github.com/appc/acbuild/blob/master/examples/nodejs/build-nodejs.sh#L19

I think that this is the best solution than others as forking this repo only for that purpose; there's actually [a fork for that](https://github.com/RepublicWealth/docker-alpine-node) but is out of date and I think that for you only would be to setup a free account in quay.io and register the hook.

Thanks for considering.

**Comment by ifraixedes** [comment]
Please let me know if there is a chance that you add this to quay.io otherwise I look for another solution.

Thanks in advance.

**Comment by mhart** [comment]
If there's no maintenance, then I'm happy to look into this. At the moment it seems that quay.io requires permissions to my private repos (and private organization repos), which I'm not going to grant. (Docker Hub doesn't require this)

If you know of any way to setup a webhook and just give them access to my public repos, please let me know!

**Comment by ifraixedes** [comment]
Ok, I didn't know that it requires those permissions.
I'll take a look around to see if there's any other solution to use this same repo without giving those.

Thanks

**Comment by ifraixedes** [comment]
Investigating a bit, and testing with a fork of your repo, there's no way to auto trigger the build based on new pushes because the option which doesn't require to have any github authorization is using custom git webhook, whose payload has a slightly different JSON schema than the one used by Github.

I could do a fork of your repo and synchronize it, but the private permissions is disencouraging, so if you wouldn't mind to add a public SSH key as a deploy key with read only access to this repo, then I would be happy to run the trigger manually every time that you make an update, because my only interest is in the last Node, the one that you usually keep on Master and I don't pretend to create each version.

This is has been the result to do so with the mentioned fork for testing purpose https://quay.io/repository/ifraixedes/alpine-node-do-not-use

What do you think?

**Comment by mhart** [comment]
@ifraixedes it's a pity it requires those permissions because that's not what GitHub OAuth requires to trigger a service (this is how you can do it with Docker Hub with only public access). Perhaps they'll add that as an option in the future?

Can you explain the deploy key option in a bit more detail?

**Comment by ifraixedes** [comment]
I will try to reach them by email regarding this issue and we'll see if they may want to consider to add it.

Regarding the deployment key; you can add on each Github repository public SSH keys for deployment purpose (they are call deploy keys and you can see that section in the settings of the repo).

Quay.io pull the repository in order to build the image from the Dockerfile, so it uses a key which is the counterpart of public key; the public key allows to Quay.io to access to the repo and pull it each time that trigger a build. This is how other services like CIs also work.

I attached a screenshot of the dialog that I got when I setup the test with my fork and where the public key is shown.

![screen shot 2016-06-13 at 18 52 37](https://cloud.githubusercontent.com/assets/1731633/16021409/cc092de0-31b2-11e6-8e03-8db062c76f7b.png)

**Comment by mhart** [comment]
So weird – why don't they just use https? Then they wouldn't need an SSH key!

Anyway, happy to add one if you like – you can add it here or DM it to me on Twitter: @hichaelmart

**Comment by ifraixedes** [comment]
I try it with https today's evening without an ssh key. I didn't come up with that :(

**Comment by mhart** [comment]
I think this might be working now...? I temporarily allowed quay.io private access, it added a webhook to my repo and then I revoked the private access.

I just (re)pushed some tags and I think they might be building successfully:

https://quay.io/repository/mhart/alpine-node?tab=builds

**Comment by ifraixedes** [comment]
So far they haven't finished, so I'm not sure if they will succeed.
I tried the HTTPS option and works; Quay.io gives you a SSH key even though you set HTTPS, but I didn't added it to the repo and the build succeeded.

If works your experiment it's better than this one, because the builds have to be triggered manually.

By the way, I contacted with Quay.io, they told me if we could use the generic web hooks with Github, but that isn't possible, because they don't have the same payload and Quay.io response with 400 to Github requests.

**Comment by mhart** [comment]
So far they're succeeding... just slowly! (this is the same with Docker Hub tbh – it takes forever to build – and they don't seem to recognise that certain tags point to the same commit so they try to build each separately!)

I'm going to close this – I think it's all working 👍 

Thanks for the nudge!

**Comment by ifraixedes** [comment]
Thank you for considering and for your effort.

Now I can use this image directly with `acuild` because quay.io serves them as the [App Container Spec defines](https://github.com/appc/spec/blob/master/spec/discovery.md)

**Comment by mhart** [comment]
@ifraixedes no probs – I'm interested to see how the App Container spec goes actually, and acbuild looks quite interesting – it's good to have some competition in this space.

I'm looking forward to the day where I can build and run containers without needing special privileges – and without any special software installed at all (ie, self-contained executables)!
