### ISSUE TITLE
Add Python installation for node-gyp functionality

### ISSUE THREAD

**Issue by mboudreau** [mhart/alpine-node#43]
I was getting an issue where a module would fail to build causing dependency hell.  All that needed to be done is adding this one line:

`RUN apk add --update python` 

I'll create a PR for this.  I think it would be nice to have it included with this image since node-gyp is something used often within node.

**Comment by mboudreau** [comment]
Wait, I can see in your dockerfile that python is there, but it doesn't seem to be available when using the 4.4 image.  I'll investigate further.

**Comment by mboudreau** [comment]
Ah, you're removing it after building.  I'll create a PR that doesn't do that.

**Comment by mhart** [comment]
Dupe of #27

**Comment by mboudreau** [comment]
Good conversation.
