### ISSUE TITLE
Node process does not abort when it is out of memory

### ISSUE THREAD

**Issue by doganyazar** [mhart/alpine-node#44]
My node process does not exit (aborted) when it is out of memory. Instead it just prints 

```
<--- Last few GCs --->

    1095 ms: Mark-sweep 27.4 (62.7) -> 21.2 (59.4) MB, 33.0 / 0 ms (+ 5.5 ms in 42 steps since start of marking, biggest step 0.4 ms) [allocation failure] [GC in old space requested].
    1114 ms: Mark-sweep 21.2 (59.4) -> 21.2 (59.4) MB, 19.1 / 0 ms [allocation failure] [GC in old space requested].
    1132 ms: Mark-sweep 21.2 (59.4) -> 20.9 (59.4) MB, 17.6 / 0 ms [last resort gc].
    1149 ms: Mark-sweep 20.9 (59.4) -> 20.9 (59.4) MB, 17.5 / 0 ms [last resort gc].


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x1767b25c9e59 <JS Object>
    2: _repeat [/usr/src/app/memory.js:~10] [pc=0x54102d5f9b1] (this=0x3cc32928c999 <a Timeout with map 0x34877b623bb1>)
    3: _onTimeout(aka wrapper) [timers.js:417] [pc=0x54102d5d7b3] (this=0x3cc32928c999 <a Timeout with map 0x34877b623bb1>)
    4: tryOnTimeout(aka tryOnTimeout) [timers.js:224] [pc=0x54102d5d4e3] (this=0x1767b2504189 <undefined>,timer=0x3cc32928c999 <a Timeout with map 0x348...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
```

and then starts using 100% CPU. 
This is a serious safety issue. Is this expected due to difference with glibc and musl? 

When I try it with node:argon container exits as expected after printing the same information as above.

To mimic the behaviour, I have created a Dockerfile and a js file that leaks memory:
[memory.zip](https://github.com/mhart/alpine-node/files/314232/memory.zip)

**Comment by mhart** [comment]
I have no idea I'm afraid – this build does nothing special as far as I'm aware – it just uses the source straight from Node.js to compile, so I suspect it's either an issue with the Node.js source, or the way Alpine manages processes?

In either case, I don't think there's anything that can be done about it in this project?

**Comment by doganyazar** [comment]
Thank you very much for your quick answer. I just could not figure out the correct forum to state this problem. Do you have a suggestion? 

Closing issue anyway.
