### ISSUE TITLE
Add instructions to Dockerfile example to build native dependencies without significantly increasing image size. 

### ISSUE THREAD

**Issue by Praisebetoscience** [mhart/alpine-node#47]
Building node-gyp has come up a few times in the issues, and I understand that including the tools to build it adds significantly to the image size, making it larger than even the `slim` images from the official node builds. 

However the current readme example installs the dev tools to an intermediate layer, which makes it impossible to clean up and keep the image size low without using an external squash program.   

If you want to clean up the dev tools after `npm install`, you need to execute it all on a single `RUN` command to prevent docker from creating bloated intermediate layers.  There are two options, a one line script chained together with `&&` or including a ash build script in your repo then calling that with `RUN`.  

The first option is likely sufficient.  For example:

```
RUN apk add --no-cache make gcc g++ python && \
    npm install && \
    npm cache clean && \
    apk del make gcc g++ python
```

Including this in the readme might help some of those looking to use this image (thanks btw, love it!) but still need to build node-gyp.

**Comment by SimenB** [comment]
Thanks for this @Praisebetoscience! It should be `RUN apk add --no-cache` etc, but figured that out quickly 😄

**Comment by alexhultman** [comment]
I don't know what you're talking about. I just swapped from node:slim (close to 400mb) to mhart/alpine-node (47 mb). I was able to successfully build native npm modules.

**Comment by deepsweet** [comment]
you can achieve the same result with `--virtual`:

```
RUN apk add --no-cache --virtual .build-deps make gcc g++ python && \
    npm install && \
    npm cache clean && \
    apk del .build-deps
```

**Comment by silverwind** [comment]
This should probably be highlighted somewhere visible in the README. Until today, I was blissfully ignoring the fact that native modules need build tools, which lead to my dependency loading a prebuild glibc-built binary without me noticing (it apparently even worked like 50% of times 😆).

**Comment by mhart** [comment]
@silverwind this issue is specifically related to the native deps / npm install being squashed in a single layer or not – the README has instructions on what to do if you have native deps already: https://github.com/mhart/alpine-node#example-dockerfile-for-your-own-nodejs-project

**Comment by silverwind** [comment]
@mhart Hmm yeah, that's probably sufficient. Still won't hurt to have the removal of the tools in the sample.

By the way: Did anyone research on how to cleanly remove `npm` after module installation?

**Comment by deepsweet** [comment]
> Did anyone research on how to cleanly remove npm after module installation?

```
npm uninstall -g npm
```

😄

**Comment by silverwind** [comment]
Ah, so simple, thanks 👍

**Comment by silverwind** [comment]
Might not be as simple as that because of npm bugs. 

When I do `npm cache clean && npm uninstall -g npm` in a single chained `RUN` statement, it seems `npm cache clear` actually deletes `/root` (it's totally empty) and then `npm uninstall` complains about not being able to stat `/root`.

I filed https://github.com/npm/npm/issues/14008 and worked around it through `rm -rf /root/.npm && npm uninstall -g npm`.

Edit: and https://github.com/npm/npm/issues/14012 for the cache clear bug.

**Comment by jazlopez** [comment]
Good point on deleting build tools after install native extensions; 
I also join to the request for the maintainer to add the instructions on how to delete the build tools to keep the image smaller.

**Comment by SimenB** [comment]
`docker build` now accepts `--squash`, so no reason to do it in a single big chain anymore, layers are just kept for local caching, the pushed image is a single layer atop `FROM` already

**Comment by markg85** [comment]
Just sharing how i do this in case it might help someone else.

I have a couple of nodejs projects running in alpine-node containers as micro services. Some of them need to compile a library (in this case fast-xml2js). At first, i was adding the build tools to the container in question and compiling it in there. It works, but kinda makes the containers bigger then needed and is a hassle when updating containers for newer versions.

So i made one new "dev" container. Also still a alpine-node one, but with build tools in. I use that container to do "npm install" and compile any needed data. The folder i do "npm install" in is just a folder mounted from the host, i use that very same folder in other containers which then suddenly have the compiled binaries at their disposal.

Works like a charm and maintains small containers :) I still have to go through some hoops when updating containers, but now i only need to do extra work for the "dev" container to rebuild binaries.

**Comment by mhart** [comment]
This should be addressed on the most recent README which has instructions on multi-stage builds: https://github.com/mhart/alpine-node#example-dockerfile-for-your-own-nodejs-project
