### ISSUE TITLE
image size so large?

### ISSUE THREAD

**Issue by gatspy** [mhart/alpine-node#50]
Why build your dockerfile , very large image.

**Comment by mhart** [comment]
I'm sorry I don't understand your question?

**Comment by gatspy** [comment]
Thanks for sharing.
 i build image form your dockerfile, after completion,the image size more than 300M.

**Comment by mhart** [comment]
You don't need to build the image – you can find them here: https://hub.docker.com/r/mhart/alpine-node/tags/

**Comment by gatspy** [comment]
Thank you for your suggestion.

**Comment by mhart** [comment]
I just rebuilt the Dockerfile and the image size is exactly what it says in the README, so I'm going to close this.

I suspect you must have changed something in the Dockerfile?
