### ISSUE TITLE
docker is not updated with 6.3.1

### ISSUE THREAD

**Issue by freiit** [mhart/alpine-node#53]
Can you please kick your docker repository, so we get the newest 6.3.1 build?
(https://hub.docker.com/r/mhart/alpine-node-auto/)

Thanks :)

**Comment by mhart** [comment]
Oh, how weird – thanks for the prod! Had to delete all the latest git tags and push them again. Should be all good now:

https://hub.docker.com/r/mhart/alpine-node-auto/builds/

**Comment by freiit** [comment]
Took docker a while, but 6.3.1 is now available. Thanks :)

**Comment by freiit** [comment]
Ups. npm is missing in the 6.3.1. 
I'm waiting for the next build. Should be ready in approx 8 hours... hope its fixed in that build?
