### ISSUE TITLE
docker mhart/alpine-node-auto:6.3.1 does not include npm

### ISSUE THREAD

**Issue by freiit** [mhart/alpine-node#54]
Hi, according to the docs (and in consistency with 6.3.0) it should contain `npm`, but:

```
~$ docker run -ti --rm mhart/alpine-node-auto:6.3.1 sh
/ # npm
sh: npm: not found
/ # find . -name npm
/ # 
```

Can you please rebuild?

**Comment by mhart** [comment]
Hmmm, looks like there was an error with the most recent build: https://hub.docker.com/r/mhart/alpine-node-auto/builds/bmpqgxjdeevqrn9jfiqyaty/

Will rebuild now.

**Comment by mhart** [comment]
Ok, just force pushed that tag again. Btw, `6.3`, `6` and `latest` should all work in the meantime.

It's very frustrating that the Docker Hub doesn't notify you of broken builds or anything – I had no idea that those tags hadn't built until you opened the issue.

**Comment by freiit** [comment]
Yep - that and the build speed. Definitely something docker could work on :)

Anyways, its working now! :)

Thanks, \C

**Comment by mhart** [comment]
Glad to hear it! Please let me know if it happens again 👍

**Comment by mhart** [comment]
Btw – there have been automated builds at quay.io for a while now as well – which seem to be a little more stable (and quicker): https://quay.io/repository/mhart/alpine-node

Just in case you'd prefer that option
