### ISSUE TITLE
Add onbuild images?

### ISSUE THREAD

**Issue by ozbillwang** [mhart/alpine-node#56]
Compare with official node images, I can't find any mhart/alpine-node with tag of `onbuild`, which is useful.

For example,

```
FROM mhart/alpine-node:4

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

ONBUILD COPY package.json /usr/src/app/
ONBUILD RUN npm install
ONBUILD COPY . /usr/src/app

CMD [ "npm", "start" ]
```

Could you plan the onbuild image as above for all version?

**Comment by mhart** [comment]
This image was never intended to reproduce the official node images, so saying that onbuild tags of some kind are "missing" is a bit of a stretch.

That said, I appreciate that some might find them useful – but my experience with this project has shown me that most people who use it want to craft their own custom images – and as you've shown, it's very easy to create your own.

There's a fair bit of overhead maintaining extra tags, and this would add at least 11 more (2 for v0.10, 2 for v0.12, 3 for v4, 4 for v6). The 22 tags that currently exist are already painful enough to manage (automated builds often don't trigger when you push multiple tags, and the more there are, the longer they sit in the queue)

So, unless there's a lot more demand for this, I'm not going to add it for now – I'll leave this open as a question in case there's a lot more people out there who want the same thing

It's likely that there'll be official Node.js images on Alpine soon, so it may very well be that they add support for this themselves!

**Comment by ozbillwang** [comment]
understood. Let see if anyone votes for my idea.
