### ISSUE TITLE
bower installation fails

### ISSUE THREAD

**Issue by keymsg** [mhart/alpine-node#59]
Hi there, I am trying to run node web server for my website and it seems that while installing bower packages it fails complaining bower not found. I have included npm install -g bower command before installing the dependent packages. Could you please help?

Thanks.

**Comment by mhart** [comment]
Hi @keymsg – what does your Dockerfile look like? It seems to work fine for me:

``` console
$ docker run mhart/alpine-node sh -c 'npm install -g bower && bower --version'
/usr/bin/bower -> /usr/lib/node_modules/bower/bin/bower
/usr/lib
`-- bower@1.7.9

1.7.9
```

**Comment by keymsg** [comment]
Hi @mhart, this is my Dockerfile.

FROM mhart/alpine-node:latest
ENV NODE_ENV=development PORT=8080
COPY /src/api/account   /var/www/account-api
WORKDIR /var/www/account-api
RUN npm install -g bower &&  npm install
CMD ["npm", "start"]
EXPOSE $PORT

I noticed the build log and yes bower is installed but somehow one of the dependencies couldn't go through. And I doubt that it may require some more packages in the image or node/npm version doesn't match to what is expected by the dependent package (moment-recur in this case).

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm WARN Api.Student@1.0.0 No description
npm WARN Api.Student@1.0.0 No repository field.
npm WARN Api.Student@1.0.0 license should be a valid SPDX license expression
npm ERR! Linux 4.4.15-boot2docker
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE

npm ERR! moment-recur@1.0.5 postinstall: `bower install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the moment-recur@1.0.5 postinstall script 'bower install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the moment-recur package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     bower install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs moment-recur
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls moment-recur
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/student-api/npm-debug.log
The command '/bin/sh -c npm install -g bower &&  npm install' returned a non-zero code: 1

Appreciate your help. Thanks

**Comment by mhart** [comment]
@keymsg looks like there's an issue for this posted here: https://github.com/c-trimm/moment-recur/issues/47

Looks like the workaround is to add a `.bowerrc` to your project root with `{ "allow_root": true }`

Going to close this at it's an issue with `moment-recur` and/or `bower` – hope you solve it!

**Comment by keymsg** [comment]
@mhart thanks very much that indeed helped. Installing git and adding .bowerrc file fixed my issue.

thanks again.
