### ISSUE TITLE
npm v1.10.7 EventEmitter Errors

### ISSUE THREAD

**Issue by matthewhartstonge** [mhart/alpine-node#61]
Hey @mhart, thanks for this docker image, saved me a bit of time having to build this for sure!!
Are you able to do a manual dockerhub push of alpine-node:6 to include the latest npm version?

npm v1.10.7 has a horrible bug with the underlying requests lib that's cluttering docker builds with EventEmitter warnings. This is fixed in v1.10.8. See: [npm issue-13806](https://github.com/npm/npm/issues/13806)

> Both npm@2.15.10 and npm@3.10.7 released with the update to request@2.74.0 which seems to be causing this warning

Ahha! See you already commented on [npm issue-13656](https://github.com/npm/npm/issues/13656) 💃

**Comment by mhart** [comment]
Right, it's a pity that v3.10.8 also has some issues:

https://github.com/npm/npm/issues/14042
https://github.com/npm/npm/issues/13918

(although the latter is possible only Mac-specific)

Hopefully 3.10.9 will be out soon!

**Comment by matthewhartstonge** [comment]
💩  True.. Never mind then haha - Thanks @mhart!
(Feel free to close, since It's upstream)

**Comment by mhart** [comment]
Bit the bullet: v3.10.8 is now included w/ alpine-node:6

**Comment by matthewhartstonge** [comment]
Thanks! 😄
