### ISSUE TITLE
postinstall does not work (for typings)

### ISSUE THREAD

**Issue by fletort** [mhart/alpine-node#63]
Here my docker file:

> FROM mhart/alpine-node:latest
> RUN npm install -g typescript
> WORKDIR /src
> CMD npm install && npm start

in my package.json file i get the folloing postinsall script:
`"postinstall": "typings install",`

then i got the following error
`postinstall: cannot run in wd %s %s (wd=%s) angular2-quickstart@1.0.0 typings install /src`

**Comment by mhart** [comment]
I don't think this is related to this Alpine image?

I don't know what that error is – but is it because you're running as root? If you Google for that error you'll see a lot of ppl having similar issues.

Try: `npm install --unsafe-perm` or change the `USER` in your Dockerfile and see how you go.
