### ISSUE TITLE
ARM version?

### ISSUE THREAD

**Issue by silverwind** [mhart/alpine-node#64]
Any interest in doing a ARM version of `alpine-node`, e.g. `armhf-alpine-node`?

You'd need some hardware (a RPi 2 is good enough) and a different base image so correct binaries are produced (`container4armhf/armhf-alpine` is a good base image), but other than that Dockerfile works as-is.

**Comment by mhart** [comment]
Hmmm, no interest from me unfortunately – I don't have any ARM devices (I mean... any development devices 😄 )

Would be happy to link to any project that did do this though!

**Comment by silverwind** [comment]
I thought about doing it, but the maintenance required put me off so far. Maybe if this project would get recognition from the Node.js foundation they could provide some form of automated infrastructure to build those images.

**Comment by airtonix** [comment]
You generally don't  need to worry about this now, as the official node images have both arm and alpine builds (sometimes a combination of both).

this file indicates what architectures get what base OS : https://github.com/nodejs/docker-node/blob/bf84a38aeacb4f6aad34e07c79fd3a0084da5cd2/architectures

I've successfully tested the following on a rpi2 running hypriot: 

```
$ docker run -H 192.168.0.5 --rm -it node:8-alpine uname -a
Linux b2d71080eb7a 4.4.50-hypriotos-v7+ #1 SMP PREEMPT Sun Mar 19 14:11:54 UTC
2017 armv7l Linux
```

Which seems to contradict that architecture file, which (as I interpret it) shows that alpine builds are not available for armv71... but as you can see... the reality is that I just ran one.

**Comment by silverwind** [comment]
It is now possible to cross-build docker images, so hardware is no longer needed. It works pretty much out of the box on macOS, just need to build `FROM arm32v6/alpine`, which seems to be the right image for RPi (no idea why it isn't called `arm32v7`). Getting multiple architectures published under the same is non-straightforward, thought.
