### ISSUE TITLE
Cannot install any packages

### ISSUE THREAD

**Issue by blocka** [mhart/alpine-node#66]
```
Step 6 : RUN apk add --update git
 ---> Running in 9cebf5b77483
fetch http://dl-cdn.alpinelinux.org/alpine/v3.4/main/x86_64/APKINDEX.tar.gz
ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.4/main: BAD signature
WARNING: Ignoring APKINDEX.167438ca.tar.gz: No such file or directory
fetch http://dl-cdn.alpinelinux.org/alpine/v3.4/community/x86_64/APKINDEX.tar.gz
ERROR: unsatisfiable constraints:
  git (missing):
    required by: world[git]
The command '/bin/sh -c apk add --update git' returned a non-zero code: 1
```

**Comment by mhart** [comment]
Do you mean `apk add --no-cache git`?

**Comment by mhart** [comment]
Looking more deeply at your error – it looks like it might be a problem with the signature coming from `http://dl-cdn.alpinelinux.org/alpine/v3.4/main` ?

**Comment by blocka** [comment]
Seems only to be an issue on my local machine. When I deploy it works fine. What can I do locally, though?

**Comment by mhart** [comment]
No idea – something to do with your networking setup perhaps?

Pretty sure it's not related to this image though – does the same thing happen with the `alpine:3.4` image?

**Comment by mhart** [comment]
@blocka let me know if the same thing happens on the normal alpine image – if so, it's not related to this image

**Comment by blocka** [comment]
Sorry to keep your issue list dirty...I haven't had time to play with this,
and it's working in other places, so I've just ignored it.

**Comment by vielmetti** [comment]
There was a build issue just resolved.

https://bugs.alpinelinux.org/issues/6389

for at least some architectures, worth looking at this to see if it addresses the problem.

**Comment by mhart** [comment]
No news on this in a while, going to close – @blocka feel free to reopen if you have anything actionable 👍

**Comment by Ghayyas** [comment]
Same issue with me.. I cant install anything

**Comment by krysalead** [comment]
Hi,

Same for me, I can install git on the image, I am using Jenkins to run the image.

> ERROR: unsatisfiable constraints:
  git (missing):
    required by: world[git]

EDIT: It worked after another run and using your command **apk add --no-cache git**
