### ISSUE TITLE
NPM dependencies in Git

### ISSUE THREAD

**Issue by whitlockjc** [mhart/alpine-node#68]
NPM allows you to specify dependencies that live in a Git repository but if you attempt to package a node.js application that does this, you run into an error because `git` isn't installed.  I'm not asking you to package `git` but if you don't want to support this type of node.js module, how would _you_ work around this?

**Comment by LoicMahieu** [comment]
Like the [example in the readme](https://github.com/mhart/alpine-node#example-dockerfile-for-your-own-nodejs-project), you can simply install dependencies before `npm install`.
Most of time, after `npm install`, you don't need theses dependencies in your image. You could `apk add`, `npm install` and `apk del` in the same layer:

``` Dockerfile
RUN apk add --no-cache git && \
    npm install && \
    apk del git
```

**Comment by whitlockjc** [comment]
My apologies for not noticing the example, much appreciated.
