### ISSUE TITLE
Node v6.9.1

### ISSUE THREAD

**Issue by jpadilla** [mhart/alpine-node#69]
Would it be possible to build and publish Node v6.9.1 whenever you get a chance. Thanks!

https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V6.md#6.9.1

**Comment by mhart** [comment]
Thanks! Pushed as of https://github.com/mhart/alpine-node/commit/2c1e8271e375293955affcc76dca11da02ce8c26
