### ISSUE TITLE
Wrong node version

### ISSUE THREAD

**Issue by anaibol** [mhart/alpine-node#70]
Hi, after running `docker run mhart/alpine-node node --version` I am getting `v5.8.0`.
I tried with `:latest` or even `:7` removing all docker images with `docker rmi $(docker images -q)`.
Any idea of what could cause that?

Thanks!

**Comment by mhart** [comment]
@anaibol have you pulled down the latest version? Try `docker pull mhart/alpine-node` and then see if you have some more success with the `run` command

**Comment by anaibol** [comment]
Oh thanks! I am sorry, it was not an issue related with alpine-node but with my ignorance of docker..
