### ISSUE TITLE
node 6.9.1 or 7.x , alpine-node takes more time - atleast 20 mins - to get the first build on a nice MAC configuration

### ISSUE THREAD

**Issue by rasekar2000** [mhart/alpine-node#72]
Hello @mhart & Team, 

 It takes almost 20 mins+ to get the first build ready in the alpine - node on a decent MAC .
 How much time it typically takes for the community ? Please let me know any other insights. 

Thanks and Regards,
Raj

  CXX(host) /node-v6.9.1/out/Release/obj.host/icutools/deps/icu-small/source/common/locbased.o
  CXX(host) /node-v6.9.1/out/Release/obj.host/icutools/deps/icu-small/source/common/messagepattern.o
  CXX(host) /node-v6.9.1/out/Release/obj.host/icutools/deps/icu-small/source/common/util_props.o
  CXX(host) /node-v6.9.1/out/Release/obj.host/icutools/deps/icu-small/source/common/servrbf.o
  CXX(host) /node-v6.9.1/out/Release/obj.host/icutools/deps/icu-small/source/common/uinit.o
  CXX(host) /node-v6.9.1/out/Release/obj.host/icutools/deps/icu-small/source/common/rbbistbl.o
  CXX(host) /node-v6.9.1/out/Release/obj.host/icutools/deps/icu-small/source/common/uniset_props.o
  CXX(host) /node-v6.9.1/out/Release/obj.host/icutools/deps/icu-small/source/common/uloc_keytype.o
  CXX(host) /node-v6.9.1/out/Release/obj.host/icutools/deps/icu-small/source/common/unorm.o
  CXX(host) /node-v6.9.1/out/Release/obj.host/icutools/deps/icu-small/source/common/unistr_case.o
  CXX(host) /node-v6.9.1/out/Release/obj.host/icutools/deps/icu-small/source/common/brkeng.o

**Comment by mhart** [comment]
@rasekar2000 is there a reason you're compiling from scratch? It shouldn't take that long if you're following the example on the README:

https://github.com/mhart/alpine-node#example-dockerfile-for-your-own-nodejs-project

**Comment by mhart** [comment]
Closing this, doesn't seem to be an issue with the image
