### ISSUE TITLE
Building node binary statically avoids to load native extensions

### ISSUE THREAD

**Issue by Flarna** [mhart/alpine-node#75]
I tried to load a native extension using your docker containers for node 0.10.48, 0.12.17, 4.7.0 and 6.9.2 but it works only with the container for 0.10.48.
The newer node binaries seem to be statically linked and therefore loading of shared objects (.node files) is not possible anymore.

Is there a special reason to avoid the use of native extensions?

**Comment by mhart** [comment]
Which images are you using? Not the `base-` ones are you?

**Comment by Flarna** [comment]
I used the base- images as I have already prebuilt binaries for alpine ready and therefore no need for npm,... inside container.
I found meanwhile that using the "full" images works for me.

**Comment by mhart** [comment]
@Flarna right, the base images are statically compiled – you shouldn't use them with native modules

**Comment by soulne4ny** [comment]
It would be nice to have it stated clearly in the README and docker hub!

@Flarna, I wonder how much time it took for you to discover the reason?

BTW, What's the cost of having non-static node in the base images?
