### ISSUE TITLE
Question: alpine-node docker image build automation?

### ISSUE THREAD

**Issue by airtonix** [mhart/alpine-node#79]
Interested to understand how you build all those various versions of mhart/alpine-node?

there is no templating in the repo. the dockerfile has no build args.

Do you manually update the single dockerfile? what about bugfixes for old versions? semver patch level bumping?

**Comment by mhart** [comment]
There's no build automation for `mhart/alpine-node` – I update the Dockerfile on each commit: https://github.com/mhart/alpine-node/commits/master – and then build, tag and push to Docker hub.

There is an automated build that's triggered by the tags here: https://hub.docker.com/r/mhart/alpine-node-auto/

Hope that helps make things a bit clearer!

**Comment by airtonix** [comment]
Yep, thanks.
