### ISSUE TITLE
compile error vfvp2 on ARM architecture(+fix)

### ISSUE THREAD

**Issue by coderofsalvation** [mhart/alpine-node#8]
Hi,

I tried to get this dockerfile crosscompiled on ARM as well, but got errors.
This seems to fix it:

https://github.com/coderofsalvation/alpine-node/commit/71ff95be0620a1c8a60c8c1ea83ee719de048e65

It seems nodejs needs --without-snapshot and vfvp3 as a minimum, otherwise it crashes on ARM
Not sure if and how we should merge this.
In any case, people who want it can grab the dockerfile here:

https://github.com/coderofsalvation/alpine-node-arm

or the precompiled tarball here:

https://github.com/coderofsalvation/alpine-node-arm/raw/master/node-v4.1.1-armhf-alpinelinux.tar.gz

**Comment by silverwind** [comment]
If I recall correctly, these two issues should be fixed in the lastest node version, at least on `stable`.

@coderofsalvation could you retry?

**Comment by mhart** [comment]
I believe this has been fixed too – going to close, but if it's still an issue, happy to reopen
