### ISSUE TITLE
Install node through an APKBUILD

### ISSUE THREAD

**Issue by silverwind** [mhart/alpine-node#81]
So, in https://github.com/yarnpkg/yarn/issues/1326#issuecomment-276862986 it was noticed when one tries to install `yarn` through `apk` in this container, another (older) version of `node` is pulled in as a dependency which of course isn't ideal.

Would it be possible to install the compiled `node` through an `APKBUILD` instead of `make install`, so that `apk`'s dependency resolution detects `node` as being installed when installing `yarn`?

**Comment by mhart** [comment]
@silverwind I'm not sure what you mean – there's already an apk package for Node: https://pkgs.alpinelinux.org/package/v3.5/main/x86_64/nodejs – see here for the APKBUILD file: http://git.alpinelinux.org/cgit/aports/tree/main/nodejs/APKBUILD

This repo/image is for a prebuilt Node – one that doesn't use apk (I created it basically because the Alpine package was behind for a long time on Node.js releases – they're much better now)

**Comment by mhart** [comment]
Basically what I'm saying is if you want an Alpine image with node managed by apk, then all you need is this:

```Dockerfile
FROM alpine:3.5

RUN apk add --no-cache nodejs
```

(untested... but something like that 😄 )

**Comment by mhart** [comment]
And if the `yarn` apk package depends on `nodejs`, then you should just be able to get yarn and node like this:

```Dockerfile
FROM alpine:3.5

RUN apk add --no-cache yarn
```
(or whatever the yarn package is)

**Comment by mhart** [comment]
(apologies if I closed this too hastily – maybe I'm just not understanding what you mean? Or what you're trying to achieve)

**Comment by silverwind** [comment]
The issue is that the `nodejs` package is installed and `node` is downgraded when installing `yarn` because it isn't recognized by `apk`:

````
$ docker run -it --rm mhart/alpine-node:base sh
/ # node -v
v7.5.0
/ # echo http://dl-cdn.alpinelinux.org/alpine/edge/testing >> /etc/apk/repositories
/ # apk add --no-cache yarn
fetch http://dl-cdn.alpinelinux.org/alpine/v3.5/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.5/community/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/edge/testing/x86_64/APKINDEX.tar.gz
(1/9) Installing ca-certificates (20161130-r0)
(2/9) Installing libcrypto1.0 (1.0.2k-r0)
(3/9) Installing libgcc (6.2.1-r1)
(4/9) Installing http-parser (2.7.1-r0)
(5/9) Installing libssl1.0 (1.0.2k-r0)
(6/9) Installing libstdc++ (6.2.1-r1)
(7/9) Installing libuv (1.9.1-r0)
(8/9) Installing nodejs (6.9.2-r1)
(9/9) Installing yarn (0.20.0-r0)
Executing busybox-1.25.1-r0.trigger
Executing ca-certificates-20161130-r0.trigger
OK: 66 MiB in 20 packages
/ # node -v
v6.9.2
````

**Comment by silverwind** [comment]
And because the `yarn`package authors don't think that removing the `nodejs` dependency here is a good solution, we have to get `apk` to recognize the hand-compiled `nodejs`.

**Comment by mhart** [comment]
Right – because it's a completely custom build – I don't think I want to start conflicting with official apk packages.

I'll leave a comment on the yarn issue – but basically I think it's easiest if you're using a custom build of Node.js (like this image) instead of apk, then it's best to manually install yarn too instead of using apk.

**Comment by mhart** [comment]
Manual installing is very easy – either `curl -o- -L https://yarnpkg.com/install.sh | sh` or use the tarball from `https://yarnpkg.com/latest.tar.gz`

**Comment by silverwind** [comment]
The install script seems unsuitable, it installes to `~/.yarn` and tries to add itself to `~/.profile` instead of doing a system-wide installation like the apk pagage does.

The tarball looks like it could work if one extracts it to `/opt` or something, but it'll be quite a bit of manual work to get it to work like the apk package.
