### ISSUE TITLE
Remote debugging?

### ISSUE THREAD

**Issue by fetherolfjd** [mhart/alpine-node#82]
Do these images support remote debugging of the application being run in Node.js? We were using debian as our base before, and have switch over to this alpine-node as the base for our boxes, since switching I haven't been able to get my remote debugger attached anymore. We're pointing to alpine-node:6.9.5. Thanks.

**Comment by mhart** [comment]
These images don't do anything in particular related to remote debugging – they're just a basic build of Node.js on Alpine Linux (ie, essentially `./configure && make && make install`)

You can see the Dockerfile for 6.9.5 here: https://github.com/mhart/alpine-node/blob/e621e52ee0b0202165a8e78b3fbfcbf32345d52b/Dockerfile

**Comment by fetherolfjd** [comment]
That's what it seemed, but I wanted to be sure. We've got a nicely hidden problem somewhere in our chain of docker images then. Thanks for the fast reply.
