### ISSUE TITLE
gpg: keyserver receive failed: Address not available

### ISSUE THREAD

**Issue by marciomsm** [mhart/alpine-node#84]
I am trying to generate a docker image to node 6.10 with alpine, but I get this error:

**gpg: keyserver receive failed: Address not available**

Does anyone knows how to solve it?

**Comment by mhart** [comment]
@marciomsm you're trying to compile your own image? If you just want to create your own image with Node.js 6.10 on it, you can just use:

```Dockerfile
FROM mhart/alpine-node:6.10

# whatever you want here...
```

**Comment by marciomsm** [comment]
@mhart thank you! This worked for me!
