### ISSUE TITLE
Debugging issues with latest (node v7-based)

### ISSUE THREAD

**Issue by alex-gru** [mhart/alpine-node#85]
Hi! First of all, thank you for your great work, really appreaciate it. 

I have an issue here with my environment, when using your `latest` image (node v7.9.0). [Here is my repo](https://github.com/alex-gru/course-planner).

In a few words, I use `docker-compose` to set-up 3 containers (`web` based on your image, `mongo` and `mongo-import` for running a mongo-import). When I execute`docker-compose up --build`, everything works fine, except one thing - debugging. 

In my `package.json`, I run at ` "start": "nodemon -L --debug /usr/src/app/"`
Actually, the log says` Debugger listening on [::]:5858 `. But when trying to connect via WebStorm's Note.js remote debugger, I get `Cannot establish connection - promptly closed after open`. 

As a counter-example I used your image-version `6` (node 6.10.2), here debugging works fine. 

I'm not sure where this issue comes from, be it node, alpine, or alpine-node. So excuse me in advance, if I'm bothering you.

Thanks!
Regards, Alex

**Comment by mhart** [comment]
I'm not sure either – I know that debugging has changed in the most recent version of Node.js: https://nodejs.org/api/debugger.html#debugger_tcp_based_protocol

Probably just worth checking if you can get it working on the latest Node.js without using Alpine or Docker, to narrow down the issue

**Comment by alex-gru** [comment]
Ok good idea, I'll try it with the minimal environment. 

Regarding debug with `--inspector` - I did that already (apart from the fact that I prefer debugging within the IDE), but here I only get `Websocket disconnected` messages.  [Here ](https://github.com/nodejs/node/issues/11591) is a a similar issue, which was closed. 

Anyway, thanks for your response, I'd come back if there's news.

Regards, Alex

**Comment by mhart** [comment]
Yeah, sounds from that issue like a bunch of things have changed in v7.x related to debugging – you might have to bind to a specific address or similar?

I doubt it would be related to this image as there's nothing specifically network-related being done in any of the Docker build steps – it just builds Node.js with the default options.

Good luck!

**Comment by dwong8626** [comment]
Hey guys, any luck solving this issue? I have exactly the same problem trying to debug an express app in a docker container

**Comment by alex-gru** [comment]
hey @dwong8626 - I could not get debugging running, so I'm simply using `mhart/alpine-node:6` now. see my dockerfile [here](https://github.com/alex-gru/docker-mean-ts-starter/blob/master/Dockerfile).

**Comment by dwong8626** [comment]
thanks @alex-gru I'll try using that image
