### ISSUE TITLE
Node v0.10.x support vs Alpine 3.5

### ISSUE THREAD

**Issue by samlevin** [mhart/alpine-node#86]
Firstly, awesome images! I attempted to modify the node.js v0.10.x base to use alpine 3.5 but got some weird looking symbols as output when it tried to compile node. Any idea what I have to change in order to enable this compatibility? (Note that Alpine 3.5 has 'runit' package support, for starting a process with a specific UID. I suppose that I could stay with 3.4 provided there was a way to emulate this or add this functionality to the 3.4 base)

Edit: Some of the sample output from the failing image build with alpine 3.5 base: ```                     2]L�gJ��Gŧ�,ݣd�COVb����0�����'m>k��z
���Kv+i��Ԍ�+�;�3)<ݮ��[U���
���a�%Ԃ�+/\te��������9�^�������z#�����U��O��W8�֑�_o�u���L��(�ը�k��jD�J���Q��?U��;`F^@%k� �4�O�F�!�&p �cH<9&T:
                                                                                                            &TH`���L����]B�Ӭ�U�>�ԟ����fl�P�G{����:=�����K�#*ݨ[������;������Ի݇u��]���������j0�u ��&tZ���;�Y
                            n۱��Z��7V��a��2��nR��xy�{S��#��c3�
                                                              0�"�VO�Ų`/��n8����'uO�nr��epx����Yb�V"�ju94�Ȱ�j���x>�APSF⸵������'��F���D#}�\��;���	�:�o��g$��z˿��C��~�y��S����k����B�=�cL�"�\Dbd���T���k/��d.p=��p��
�^X��w}�\u��7�wB]"�J�>�I���}��ؓ"�D�ޔ��n�T%�@��bG�t�Eh�8:���K�߸dU�8#��CvU�W�NH�赀<Q�,�����$�^*``` (and about 10k more lines)

**Comment by mhart** [comment]
No idea I'm afraid – seems quite odd!

**Comment by samlevin** [comment]
No problem! I'll close for now and update if I figure anything out. It seems like adding runit to 3.4 is the best option (for now). Thanks for the quick reply.
