### ISSUE TITLE
stipping fully-static binary saves ~11Mb

### ISSUE THREAD

**Issue by soulne4ny** [mhart/alpine-node#87]
For node from base-7.10.0 it is 27333344 vs 39535312 bytes.
As well I haven't checked how it works then yet. However it should be ok, imho.

For non-static it is less – ~5.5Mb – 31350568 vs 37301808.

**Comment by jbergstroem** [comment]
I've run stripped binaries for a while but it's a questionable optimization since it makes debugging much worse. I don't think its the right thing for the general public; if you want the extra savings you should probably consider baking your own images.

**Comment by mhart** [comment]
This is done as of the new `slim` images: https://github.com/mhart/alpine-node/commit/1dd7685bbb2ba3794bf1d6a90a6a4fa1a8d985db#diff-f6135cdd76187d8e0fd82b63ccf9327dR6
