### ISSUE TITLE
Latest image has not yarn installed despite README saying so

### ISSUE THREAD

**Issue by vampolo** [mhart/alpine-node#90]
Latest changes that brought node v8 and yarn do not fully install yarn as the installation is prevented by an if statement at [line 30 of the dockerfile](https://github.com/mhart/alpine-node/blob/master/Dockerfile#L30)

```
  if [ -z "$CONFIG_FLAGS" ]; then \
```

Proof

![image](https://cloud.githubusercontent.com/assets/294496/26706828/408fb0fa-46f5-11e7-8d95-5b4c9d85a3f9.png)

**Comment by mhart** [comment]
Works fine for me:

```console
$ docker run mhart/alpine-node:latest yarn --version
0.24.6
```

**Comment by mhart** [comment]
Are you sure you're not looking at the Dockerfile from a base image (which has a static build of nodejs with no npm or yarn)?

**Comment by nazimjamil** [comment]
What does your dockerfile look like @mhart? I'm not able to use Yarn when building with `FROM mhart/alpine-node:base-6`.

**Comment by mhart** [comment]
@nazimjamil the base images are builds of Node.js as a static binary – no npm or yarn in those builds. Use those builds for when you have no dependencies – or you just have JS dependencies that are already installed when you run `docker build`

**Comment by mhart** [comment]
@vampolo going to mark this as closed, as the latest image clearly has yarn – let me know if you can reproduce your issue

**Comment by vampolo** [comment]
@mhart yeah it is all good. Yarn is installed for root user only. as soon as i switched to another user in my dockerfile i wasn't able to use yarn anymore.
Seems not a problem strictly related to alpine-node, but it was the way i was using it.
Besides, if yarn was installed globally like npm, any user on alpine-node would not have this problem.

**Comment by mhart** [comment]
Hmmm, this is a good point – the [install script for yarn](https://yarnpkg.com/install.sh) uses the home directory, but I'm thinking it might be better to add it in a more global directory.

I'll play around with some things and update here

**Comment by mhart** [comment]
Ok, I've decided to install it in `/usr/local/share/yarn` – and symlink in `/usr/local/bin`

Have updated the `latest`, `8`, `8.0`, and `8.0.0` images with these changes

**Comment by vampolo** [comment]
Brilliant! thank you!
