### ISSUE TITLE
yarn executable missing from PATH on non-latest tags

### ISSUE THREAD

**Issue by JaKXz** [mhart/alpine-node#91]
Contrary to the documentation, I am seeing the following errors:

```bash
$ docker run mhart/alpine-node npm --version
Unable to find image 'mhart/alpine-node:latest' locally
latest: Pulling from mhart/alpine-node
2aecc7e1714b: Pull complete
e174e6f0faa3: Pull complete
Digest: sha256:3089446bbeab41e72f069749c73b7f84aeb1276fb6205102c38d378b47374746
Status: Downloaded newer image for mhart/alpine-node:latest
5.0.3

$ docker run mhart/alpine-node yarn --version
0.24.6

$ docker run mhart/alpine-node:6 npm --version
3.10.10

# ^^ this is great, but the following is the problem:

$ docker run mhart/alpine-node:6 yarn --version
container_linux.go:247: starting container process caused "exec: \"yarn\": executable file not found in $PATH"
docker: Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused "exec: \"yarn\": executable file not found in $PATH".
ERRO[0001] error getting events from daemon: net/http: request canceled
```

I think I have an idea for a fix so I'll make a PR. Thanks.

**Comment by mhart** [comment]
@JaKXz yarn was only included for images from 8.x onwards. Adding it to old images would potentially be an unwanted size increase for those already using those images.

You can see some of the discussion regarding the inclusion of yarn for 8.x onwards here: https://github.com/mhart/alpine-node/issues/65#issuecomment-293351166

**Comment by JaKXz** [comment]
@mhart fair enough, I've made #93 to clarify this in the README so people in the future aren't surprised when they see this :)

Perhaps it's a failure of communications on my part, but I was confused by the fact that `yarn` was listed for the first one so I assumed it was the same version installed across all the LTS versions as well. 

Feel free to close #93 if you feel that it's redundant, but it wasn't immediately clear to me.
