### ISSUE TITLE
Latest public builds have incorrect ownership of /usr/lib/node_modules/npm

### ISSUE THREAD

**Issue by trey-jones** [mhart/alpine-node#94]
I've really enjoyed this image for apparently 7 months or more!  Recently members of my team have pulled `mhart/alpine-node:latest` from docker hub and had some issues with permissions when installing with npm.

We've traced the problem to improper ownership on `/usr/lib/node_modules/npm`.  The newer images have ownership `501:dialout`, where older images have `nobody:root`.  Based on cursory research I'd guess that you started using NFS volumes at some point and this is causing the issue.

Thanks!

**Comment by mhart** [comment]
@trey-jones oh interesting! the change may have actually been the move from docker-machine (via VirtualBox) to Docker on Mac.

Will investigate further and let you know

**Comment by mhart** [comment]
Nope, turns out it's a bug with npm: https://github.com/npm/npm/issues/16766

**Comment by trey-jones** [comment]
Got it.  Well your container faithfully produces the latest version of npm then!  Thanks!

**Comment by mhart** [comment]
Fix for this is coming in the next version of npm, I'll update the latest 8.x images when it lands:

https://github.com/npm/npm/issues/16766#issuecomment-312053524

**Comment by mhart** [comment]
This is now fixed in the latest 8.1.3 image w/ npm 5.1.0

**Comment by nazimjamil** [comment]
I am still encountering the same issue.

**Comment by mhart** [comment]
@nazimjamil seems fine to me – I don't see `501:dialout` anywhere:
```console
$ docker run mhart/alpine-node ls -la /usr/lib/node_modules
total 12
drwxr-xr-x    3 root     root          4096 Oct 26 02:19 .
drwxr-xr-x    1 root     root          4096 Oct 26 02:19 ..
drwxr-xr-x    7 root     root          4096 Oct 26 02:19 npm
```

**Comment by nazimjamil** [comment]
@mhart How weird... my Dockerfile essentially looks like this.. Am I referencing the version of alpine-node incorrectly?

```
FROM mhart/alpine-node:8.8.1

RUN npm install node-sass --global
```

**Comment by mhart** [comment]
@nazimjamil well I'm still not sure what your symptoms are? Are you sure you're seeing the same issue as this with an ownership of `501:dialout`?

What does running this command output?

```
docker run mhart/alpine-node:8.8.1 ls -la /usr/lib/node_modules
```

I suspect you're more likely running into this issue: https://github.com/npm/npm/issues/17851

**Comment by mhart** [comment]
(in which case, just use `yarn global add node-sass` instead)

**Comment by nazimjamil** [comment]
Hi @mhart yes - you're right! Thanks for being so quick to respond!
