### ISSUE TITLE
can't get the mac address using net-tools

### ISSUE THREAD

**Issue by sanakanchha** [mhart/alpine-node#96]
I am running the image on a linux device, the application builds and runs great. However, I am not able to get the mac address even with installing the package net-tools. I compared the net-tools package for ubuntu vs alpine. I am able to get the mac address with ubuntu image though.

I looked into the package content for net-tools and see the package location is /bin/ifconfig in alpine(https://pkgs.alpinelinux.org/contents?file=&path=&name=net-tools&branch=v3.4&repo=main&arch=x86_64) vs /sbin/ifconfig in ubuntu(https://packages.ubuntu.com/xenial/amd64/net-tools/filelist).

my echo PATH output:
/home/pn/bin:/home/pn/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin

Any insights would help, thanks.

**Comment by mhart** [comment]
I don't think this is an issue with this (Node.js) image in particular – I think you'd find the same thing on the `alpine` image.
