### ISSUE TITLE
system-icu / full-icu version

### ISSUE THREAD

**Issue by ehtb** [mhart/alpine-node#97]
Thanks for the great images, 

I was wondering if you would be interested in creating an image with full-icu support, like: `./configure --with-intl=full-icu --download=all`.

See also this page: https://github.com/nodejs/node/wiki/Intl

**Comment by mhart** [comment]
Hi ehtb – thanks for the request, but I won't be creating any more images – there are already too many to manage (Node.js 0.10, 0.12, 4.x, 6.x, 8.x – with both the base statically-compiled image and the regular npm+yarn image for each one). Feel free to fork this repo and create your own of course though!
